### ISSUE TITLE
Feature Request: Pre/Post Scheme Actions

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#1025]
Scheme Pre-Actions and Post-Actions are useful for teams to do things alongside their builds such as collecting user metrics or other custom needs.

This could be as simple as additional attributes on the `xcode_schemes.scheme` structure:

```starlark
xcode_schemes.scheme(
    name = "Name",
    post_actions = [
        xcode_schemes.action(
             name = "Metrics",
             shell = "/bin/sh",
             settings_provider = "//My:App" # Not sure how important this is
             script = "//collect_metrics.sh"
        )
    ]
)
```

**Comment by brentleyjones** [comment]
I've put this in the `Post 1.0` milestone, simply because I don't see myself getting to it before 1.0. If someone contributes it before then though 💯!

**Comment by chiragramani** [comment]
I have created a PR that attempts to address this - https://github.com/buildbuddy-io/rules_xcodeproj/pull/1047. Please let me know if you have any questions/suggestions.
