### ISSUE TITLE
Bug: Test gutter diamonds don't always work

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/rules_xcodeproj#1035]
Being able to run a single test by clicking the gutter test diamonds.

**Comment by brentleyjones** [comment]
This works for me. Do you a repro where it doesn't?

**Comment by brentleyjones** [comment]
Odd. I think this feature is controlled by indexing. I wonder if you are getting indexing errors. A shareable repro would help me debug it more. I don't believe any of the example projects have this issue.

**Comment by BalestraPatrick** [comment]
@thii I assume you're on Xcode 13.x? I think some of our developers have ran into this but in Xcode 14 (and we haven't debugged it yet).

**Comment by thii** [comment]
Yes, 13.4.1.

**Comment by thii** [comment]
There is an error in the indexing log:
```
ATests.swift:4:8: error: no such module 'XCTest'
```

**Comment by BalestraPatrick** [comment]
Did you try this in the [example project](https://github.com/buildbuddy-io/rules_xcodeproj/tree/main/examples/ios_app) on your machine? Just to rule that out.
`bazelisk run //:xcodeproj` and there are some test targets in the generated project.

**Comment by thii** [comment]
I can't reproduce the error with the example project.

I think I see the difference now, the test target doesn't build in the "xcode" mode - there are no system framework search paths and testing framework search paths in the compile command.

**Comment by brentleyjones** [comment]
Can you add `test_only = True` to the library targets? I thought the latest rules_swift would require this, but maybe some still don't. Is it the primary library target of the test target? If so, I'll see if there is something I can force to work on our end.

**Comment by thii** [comment]
I figured it out. It's because we have something like [this](https://www.smileykeith.com/2021/03/04/supporting-relative-paths/) in the test target's `deps`, but didn't link it with `XCTest` (the primary library target is linked with `XCTest`). Removed that dependency and it worked.

Since there's `apple.swizzle_absolute_xcttestsourcelocation` feature now, we'll use that instead.

You can close this now.

**Comment by brentleyjones** [comment]
If you added `test_only = True` to that, did it fix it? I want to make sure the underlying error can't happen for others.

**Comment by thii** [comment]
Adding `testonly = True` to that didn't fix it.

**Comment by thii** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/pull/1039

**Comment by brentleyjones** [comment]
Do you use Quick? I think that might not work correctly for some reason.

**Comment by thii** [comment]
No, we don't use Quick.

**Comment by brentleyjones** [comment]
Okay, with that repro, I understand what was happening. By having two targets, it couldn't merge the library target into the top-level target, leaving it as a static library. Xcode will only place the checkboxes in the gutter next to tests that are part of a test target directly.
