### ISSUE TITLE
Bug: Lots of `Permission denied` errors when trying to delete Xcode's DerivedData

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/rules_xcodeproj#1048]
## Describe the bug
```
rm: /Users/thi/Library/Developer/Xcode/DerivedData/Projects-aupyeyirutuqslakjvpamkrvkaiv/Index/Build/Intermediates.noindex/bazel_output_base/execroot/__main__/bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-223d7abe647f/bin/external/Nuke/Nuke.indexstore/v5/units: Permission denied
```

## Reproduction steps
Generate a project, build, and run

```
rm -rf ~/Library/Developer/Xcode/DerivedData
```

## Expected behavior
Successfully deleted the DerivedData directory.

## Versions
- rules_xcodeproj: https://github.com/buildbuddy-io/rules_xcodeproj/commit/7ee46ec29bb4365f2c81525200a078b80bf5ca4a

**Comment by thii** [comment]
This seems unavoidable since rules_xcodeproj put a Bazel output base in there.

**Comment by brentleyjones** [comment]
Yeah. I'm not sure a better place to put the Index Build output base to avoid this. I think I might be able to nest it inside the original output base somehow.
