### ISSUE TITLE
Bug: create_xcode_overlay.sh: No such file or directory

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/rules_xcodeproj#1049]
## Describe the bug
```
PhaseScriptExecution Generate\ Files /Users/user/Library/Developer/Xcode/DerivedData/Projects-fypotnookqgqmegzxfveuwcvjqgb/Build/Intermediates.noindex/Projects.build/rules_xcodeproj/Script-13F45F77FBD42E72938E9FF1.sh (in target 'BazelDependencies' from project 'Projects')
    cd /Users/user/app
    /bin/sh -c /Users/user/Library/Developer/Xcode/DerivedData/Projects-fypotnookqgqmegzxfveuwcvjqgb/Build/Intermediates.noindex/Projects.build/rules_xcodeproj/Script-13F45F77FBD42E72938E9FF1.sh

/Users/user/app/Projects.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh: line 156: /Users/user/app/Projects.xcodeproj/rules_xcodeproj/create_xcode_overlay.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
## Reproduction steps
I'm not able to reproduce with the example project here, but here's how I got the error with our project:
1. Generate a project with `bazel` build mode
2. Build the app
3. Generate again with `xcode` build mode
4. Build the app

## Expected behavior
No error.

## Versions
- Bazel: 6.0.0-pre.20220804.3
- rules_xcodeproj: https://github.com/buildbuddy-io/rules_xcodeproj/commit/7ee46ec29bb4365f2c81525200a078b80bf5ca4a
- rules_apple: d04edf4136b4818662d7126582ec257aee372339
- rules_swift: 6153a848f747e90248a8673869c49631f1323ff3

**Comment by brentleyjones** [comment]
Since this file is created based on this check: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/tools/generator/src/Generator/CreateFilesAndGroups.swift#L600, it would seem there is a bug here, or calling it: https://github.com/buildbuddy-io/rules_xcodeproj/blob/7ee46ec29bb4365f2c81525200a078b80bf5ca4a/tools/generator/src/Generator/AddBazelDependenciesTarget.swift#L5-L19

**Comment by thii** [comment]
This only happened to me twice, I'm not able to reproduce it anymore. I'll take a look when I see it again.

**Comment by brentleyjones** [comment]
@thii Have you run into this since?

**Comment by brentleyjones** [comment]
I'm going to close this for now then.

**Comment by thii** [comment]
I've just reproduced it now. Looks like it's an Xcode's bug. Xcode doesn't reload the project if you regenerate it while keeping the project open, so I was building an BwX project with the BwB integration files (which doesn't have `create_xcode_overlay.sh`).

Seems only happens with large project.pbxproj file.

**Comment by brentleyjones** [comment]
Ahh, yeah, not sure we can do anything about that. Hopefully people aren't switching modes in the day to day (cc: @erikkerber).

**Comment by erikkerber** [comment]
😅
