### ISSUE TITLE
Feature Request: Allow adding additional files to generated project

### ISSUE THREAD

**Issue by BalestraPatrick** [buildbuddy-io/rules_xcodeproj#1055]
In some cases, we would like to add additional files to the generated project, such as ownership metadata or simply README files. 

One idea to achieve this would be to add a new attribute that accepts a list of files to add to the project. Where in the project the files would be added could be decided based on the path of the files themselves. So for example `path/to/README.md` would end up in a `path/to` group inside of Xcode.

The API could look like the following:
```starlark
xcodeproj(
    name = "xcodeproj",
    build_mode = "xcode",
    project_name = "iOS App",
    tags = ["manual"],
    top_level_targets = XCODEPROJ_TARGETS,
    additional_files = glob(["**/README"]), # add all README files to the project
)
```

What are people's thoughts on this addition? How complicated could this get?

**Comment by brentleyjones** [comment]
This is similar to XcodeGen's [Project](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#project).fileGroups, right?

I think this is reasonable. A couple questions/comments:
- What about focused projects? Do these need to be associated with a target? If so, do we want to add something to `xcode_target()` for that association, and have another attribute at the top level like you demonstrated for project-level files?
- Naming: internally we call these `extra_files`. They seem like "non-build files" or "raw files" something like that.

**Comment by BalestraPatrick** [comment]
Yes, that looks similar.

>What about focused projects? Do these need to be associated with a target? If so, do we want to add something to xcode_target() for that association, and have another attribute at the top level like you demonstrated for project-level files?

Yes that's a good point. Ideally they would need to be associated with a target, but I can see some cases that would get complicated with focused projects.

>Naming: internally we call these extra_files. They seem like "non-build files" or "raw files" something like that.
I like `extra_files` as well.

**Comment by brentleyjones** [comment]
I'm supportive of this. Let's add an optional `extra_files` to the `top_level_target()` function, and an optional `extra_files` to  `xcodeproj` macro.

On the `xcodeproj` rule I think we will need two attributes: `unowned_extra_files: attr.label_list` and `owned_extra_files: attr.label_keyed_string_dict`:

- `unowned_extra_files` will hold the list of files not associated with any targets. They will get added like this (notice the `None`): https://github.com/buildbuddy-io/rules_xcodeproj/blob/cd96c9fc6f346b9bcb7a24d0692bb6d6cd05ff68/xcodeproj/internal/xcodeproj_rule.bzl#L317
- `owned_extra_files` will have a key for each file and the value will be the the label used in `top_level_target()`. We will then only add files that have a focused target with that label, probably processing it in `_process_targets`: https://github.com/buildbuddy-io/rules_xcodeproj/blob/cd96c9fc6f346b9bcb7a24d0692bb6d6cd05ff68/xcodeproj/internal/xcodeproj_rule.bzl#L80-L83

**Comment by erikkerber** [comment]
We were just talking about this on our team yestereday.

With `owned_extra_files`, I assume that requires the association of targets-to-files to all be explicitly declared in the `xcodeproj` target?

I don't know of a great alternative, but I'm thinking about how one would implement and scale something like "Add a README file for all focused targets in the Xcode project".

**Comment by brentleyjones** [comment]
> With `owned_extra_files`, I assume that requires the association of targets-to-files to all be explicitly declared in the `xcodeproj` target?
>
> I don't know of a great alternative, but I'm thinking about how one would implement and scale something like "Add a README file for all focused targets in the Xcode project".

Yes, it would require something like this:
```
top_level_targets = [
    top_level_target(
        "//a/target:label",
        extra_files = glob(["a/target/README.md"], allow_empty = True), # Using glob here to allow the file to not exist
    ),
],
```

Which would associate that file with that target.

**Comment by brentleyjones** [comment]
They won't be set to a given target, but they will be "associated" so we can only include them when the given targets are in focus.

I'm fine with whatever external naming we want to give them.
