### ISSUE TITLE
Feature Request: Support multiple Xcode configurations

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#1059]
Currently there is only the Debug configuration in generated projects. We should support defining multiple configurations if possible.

(If possible, because currently `--config` can only be supported if the output paths don't change, since we can't transition on `--config`. One possible way around this is to generate a different sub-`spec.json` for each configuration, each from a separate `bazel build` call. This might/probably will thrash the analysis cache and will be super slow. I'm trying to think of other ways to handle this.)

**Comment by QuentinPerez** [comment]
👋  @brentleyjones, 

Do you think this feature could be included in the release `1.1` or soon after? If not, do you have a workaround for building in release mode? 

Thank you for your time 🙏

**Comment by brentleyjones** [comment]
The workaround people have been doing is changing their `rules_xcodeproj` `--config` (in `xcodeproj.bazelrc`) to have it be what they need for release mode (`-c opt` and maybe other flags), then generating the project again.

There isn't plans for it to be in the 1.1 release, as that will be dedicated to using an XCBBuildService proxy. It would be a 1.2 or later release.
