### ISSUE TITLE
Bug: BwX fails with different `top_level_targets`s

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/rules_xcodeproj#1090]
## Describe the bug

Given `//:Library` is a dependency of both `//:App` and `//:Test`.

```
xcodeproj(
    ...
    build_mode = "xcode",
    top_level_targets = ["//:App"] # `App` target builds
    # top_level_targets = ["//:App", "//:Test"] # `App` target errors with `no such module Library`
```

The `App` target builds if I add `//:Library` to `unfocused_targets`.

## Versions
- Bazel: 6.0.0-pre.20220804.3
- rules_xcodeproj: https://github.com/buildbuddy-io/rules_xcodeproj/commit/e11d1d9c799f051f9a01a948fcbebfa83b61e28a
- rules_apple: `d04edf4136b4818662d7126582ec257aee372339`
- rules_swift: `6153a848f747e90248a8673869c49631f1323ff3`

## Additional context
I'll send you the log.

**Comment by brentleyjones** [comment]
I'm still looking into this. Seems to be an issue with "automatic unfocusing".

**Comment by brentleyjones** [comment]
This was an interesting bug. Thanks for the report @thii!
