### ISSUE TITLE
Feature Request: AppCode Support

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#1113]
I am not certain how much lift this would be, but **rules_xcodeproj** generally doesn't function 100% in AppCode.

A few issues and observations:

- AppCode does not recognize schemes
- Custom LLDB init files for Bazel/rules_xcodeproj are pulled in via Schemes
- AppCode by default won't open the large-"ish" pbxproj files rules_xcodeproj generally generates

**Comment by brentleyjones** [comment]
It would be nice to support AppCore, and I think we can get around those various issues, but I see this as a "Post 1.1" type thing, falling behind Build with Bazel via Proxy in priority.

**Comment by erikkerber** [comment]
Guessing it's worth considering closing this?

https://blog.jetbrains.com/appcode/2022/12/appcode-2022-3-release-and-end-of-sales-and-support/
