### ISSUE TITLE
Bug: Unable to use test_action in xcode_schemes.scheme

### ISSUE THREAD

**Issue by canelson0202** [buildbuddy-io/rules_xcodeproj#1179]
## Describe the bug

Adding a test_action parameter to xcode_schemes.scheme, and then passing that scheme to the schemes parameter in the xcodeproj rule causes xcodeproj to break. The error description suggests adding the test target to xcodeproj's top_level_targets, but it's already been added there.

## Reproduction steps

```
_SCHEMES = [
    xcode_schemes.scheme(
        name = "scheme name",
        launch_action = xcode_schemes.launch_action(
            target = "//some/ios_application:target",
        ),
        test_action = xcode_schemes.test_action([
            "//some/ios_unit_test:target",
        ]),
    ),
]

xcodeproj(
    name = "xcodeproj",
    project_name = "name",
    tags = ["manual"],
    build_mode = "bazel",
    archived_bundles_allowed = True,
    schemes = _SCHEMES,
    top_level_targets = [
        "//some/ios_application:target",
        "//some/ios_unit_test:target",
    ],
)
```

## Expected behavior

An .xcodeproj file is generated that includes a scheme that can build/run the ios_application target as well as run the tests in the ios_unit_test target.

## Versions
- Bazel: rolling
- rules_xcodeproj: 0.7.1
- rules_apple: 1.1.0
- rules_swift: 1.0.0

## Additional context

xcodeproj works if the scheme's test_action is commented out

error message
```
Target //some/ios_unit_test:target was not found in the transitive dependencies of //path/to:xcodeproj's `top_level_targets` attribute. Did you reference an alias (only actual target labels are supported in Scheme definitions)? Check that //some/ios_unit_test:target is spelled correctly, and if it is, add it or a target that depends on it to //path/to:xcodeproj's `top_level_targets` attribute.
```

**Comment by brentleyjones** [comment]
This is fixed in 0.8.0. Before 0.8.0 you would have to use an arcane "internal" name in the scheme definition: #980.

**Comment by pswaminathan** [comment]
@brentleyjones thanks for the response! Upgrading to 0.8.0 gives us an error that index-import is trying to use Bazel's depset rule with the named items parameter, which was removed in Bazel 5.0.0. Here is a traceback:

```
ERROR: /private/var/tmp/_bazel_connor/56d1c6d8d9c9f66497fbf16bd43b929c/external/rules_xcodeproj_index_import/BUILD.bazel:3:14: in _native_binary rule @rules_xcodeproj_index_import//:index_import: 
Traceback (most recent call last):
    File "/private/var/tmp/_bazel_connor/56d1c6d8d9c9f66497fbf16bd43b929c/external/bazel_skylib/rules/native_binary.bzl", line 42, column 22, in _impl
        return _impl_rule(ctx, ctx.attr.is_windows)
    File "/private/var/tmp/_bazel_connor/56d1c6d8d9c9f66497fbf16bd43b929c/external/bazel_skylib/rules/native_binary.bzl", line 33, column 23, in _impl_rule
        files = depset(items = [out]),
Error in depset: depset() got unexpected keyword argument 'items'
```

Can you assist? Looks like an old version of bazel-skylib is getting in?

**Comment by brentleyjones** [comment]
I would make sure you upgrade your rules. Above you mention "rolling" for the bazel version, is it a recent version of 6.0-pre? If so, you should be on a newer version of rules_apple (not a released version, as those only support 5.x, you need to track `HEAD` for now). Also, there were bugs fixed in rules_swift around index-while-building, so I would use the latest released version of rules_swift as well.
