### ISSUE TITLE
Bug: lldb no longer auto completes

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#1189]
## Describe the bug

At least in BwB (I have to verify in BwX), lldb no longer has any auto completion.

## Versions
- Bazel: 14.0.1
- rules_xcodeproj: beed7163ea6168d228baeb5fd8060b0ea62216a6

**Comment by brentleyjones** [comment]
I'm not seeing this anymore. Hmm.

@chiragramani Can you let me know if you still see this, and what the repro steps are?

**Comment by chiragramani** [comment]
I was able to reproduce this yesterday when I was adding a few tests to the generator. Steps:
1. Open the project generated by `bazel run tools/generator:xcodeproj`.
2. Put a breakpoint in any of the tests.
3. When the breakpoint is triggered, `po variable.<some property name>` - the UI shows no auto-completions but the expression evaluation works all fine.

**Comment by brentleyjones** [comment]
Yeah, I have autocomplete there now 😕.

**Comment by chiragramani** [comment]
Oh okay, I tried on the latest main - sharing the exact test-case. 
![Screenshot 2022-10-03 at 12 48 36 PM](https://user-images.githubusercontent.com/11925399/193665917-9cdf38e4-efe3-49c5-aa8c-d0cc64142762.png)

**Comment by chiragramani** [comment]
It works fine for me now. I feel embarrassed that I forgot to apply the clean up drill before :)
<img width="970" alt="Screenshot 2022-10-03 at 1 11 17 PM" src="https://user-images.githubusercontent.com/11925399/193670315-151d09ae-3994-4453-87dd-e39479221d76.png">

**Comment by brentleyjones** [comment]
Yeah, I think it was an issue in Derived Data. Apparently that completion list comes from Xcode, so I bet indexing data drives it. Maybe there was a weird indexing mix up.
