### ISSUE TITLE
Bug: macos_command_line_application with linkopts has no effect

### ISSUE THREAD

**Issue by Kila2** [buildbuddy-io/rules_xcodeproj#1247]
## Describe the bug
macos_command_line_application with linkopts has no effect

## Reproduction steps
```
macos_command_line_application(
    name = "ignore",
    linkopts = [
        "-dead_strip",
    ],
    minimum_os_version = "11.0",
    visibility = ["//visibility:public"],
)
```
## Expected behavior
xcode project other link flags with contains -dead_strip or @$(DERIVED_FILE_DIR)/link.params contains -dead_strip

## Versions
- Bazel: 5.3.1
- rules_xcodeproj: 0.8.0
- rules_apple: rules_xcodeproj internal
- rules_swift: rules_xcodeproj internal

**Comment by brentleyjones** [comment]
The is for the bug report. Can you confirm if this is still an issue in 0.9.0?

If so I'll get a fix in for this over the weekend.

**Comment by Kila2** [comment]
> The is for the bug report. Can you confirm if this is still an issue in 0.9.0?
> 
> If so I'll get a fix in for this over the weekend.

I'm update xcodeproj to 0.9.0. still has this issue

**Comment by brentleyjones** [comment]
@Kila2 let me know if `main` fixes this for you.

**Comment by Kila2** [comment]
> @Kila2让我知道是否`main`为您解决了这个问题。

Work fine. Look good to me.
