### ISSUE TITLE
Bug: [BwB] TSan doesn't work from unit tests

### ISSUE THREAD

**Issue by marcelofabri** [buildbuddy-io/rules_xcodeproj#1320]
## Describe the bug

When enabling Thread Sanitizer in a unit tests' scheme (see image below), I get this error:

```
error build: Unable to copy Thread Sanitizer library: Could not determine where it lives.
```

<img width="794" alt="Screen Shot 2022-10-18 at 7 15 14 PM" src="https://user-images.githubusercontent.com/833072/196581378-750ef604-7add-4a71-9326-eb3f1102ee51.png">

When enabling it for an app, it works.

## Reproduction steps

1. Enable TSan in a unit test target's scheme
2. Run unit tests

## Expected behavior

No errors, TSan works.

## Versions
- Bazel: `bazel 6.0.0-pre.20220706.4`
- rules_xcodeproj: `0.9.0`
- rules_apple: 1.1.1
- rules_swift: 1.1.1

**Comment by marcelofabri** [comment]
I was able to repro it in the SwiftLint repo (with 0.9.0):

1. `git clone https://github.com/realm/SwiftLint.git`
2. `bazel run :xcodeproj && xed SwiftLint.xcodeproj`
3. Enable TSan for the test action of the SwiftLint scheme
4. CMD + U

I can test it later with `main`

**Comment by brentleyjones** [comment]
Hmm, it seems that it builds, but fails at runtime:

```
dyld[52166]: terminating because inserted dylib '/Users/brentley/Library/Developer/Xcode/DerivedData/SwiftLint-frzeielbsmylraavwerpyxnqgmpr/Build/Products/Debug/bazel-out/darwin_arm64-dbg-ST-6a386423d34b/bin/Tests/CLITests.xctest/Contents/Frameworks/libclang_rt.tsan_osx_dynamic.dylib' could not be loaded: tried: '/Users/brentley/Library/Developer/Xcode/DerivedData/SwiftLint-frzeielbsmylraavwerpyxnqgmpr/Build/Products/Debug/bazel-out/darwin_arm64-dbg-ST-6a386423d34b/bin/Tests/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/Applications/Xcode-14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/Users/brentley/Library/Developer/Xcode/DerivedData/SwiftLint-frzeielbsmylraavwerpyxnqgmpr/Build/Products/Debug/bazel-out/darwin_arm64-dbg-ST-6a386423d34b/bin/Tests/CLITests.xctest/Contents/Frameworks/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/usr/local/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/usr/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file)
dyld[52166]: tried: '/Users/brentley/Library/Developer/Xcode/DerivedData/SwiftLint-frzeielbsmylraavwerpyxnqgmpr/Build/Products/Debug/bazel-out/darwin_arm64-dbg-ST-6a386423d34b/bin/Tests/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/Applications/Xcode-14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/Users/brentley/Library/Developer/Xcode/DerivedData/SwiftLint-frzeielbsmylraavwerpyxnqgmpr/Build/Products/Debug/bazel-out/darwin_arm64-dbg-ST-6a386423d34b/bin/Tests/CLITests.xctest/Contents/Frameworks/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/usr/local/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file), '/usr/lib/libclang_rt.tsan_osx_dynamic.dylib' (no such file)
```

@chiragramani could you take a look at this?

**Comment by chiragramani** [comment]
Interesting. Yes, absolutely - thanks for sharing the repro, I will look into it.

**Comment by brentleyjones** [comment]
@marcelofabri This should be fixed on `main` now. Let me know if you run into more issues. Thanks for the bug report!

**Comment by marcelofabri** [comment]
Thanks! I'll double check it once 0.10.0 is released since that seems pretty close :)
