### ISSUE TITLE
Split up `target.bzl`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#136]
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/target.bzl has grown to be quite large. While everything in there doesn't really belong in any of the other `.bzl` files, it can still be split up a bit more.

**Comment by maxwellE** [comment]
@brentleyjones Is this ticket complete or should we continue to move out logic from target.bzl?
