### ISSUE TITLE
Bug: many stale files warnings

### ISSUE THREAD

**Issue by tinder-kaijing** [buildbuddy-io/rules_xcodeproj#1377]
## Describe the bug
see many stale files warnings in Xcode. Please see attached screenshot.

## Reproduction steps
to use Xcode to open generated project by using rules_xcodeproj, to do the build and run unit tests.

## Expected behavior
Developers don't want to see those stale files warnings, distract them to find real code warnings.

## Versions
- Bazel: 6.0.0-pre.20221020.1
- rules_xcodeproj: 79ac13fdf7f2aeaafd9c6ce652cc564b621a80601955e34fed8ca3292630ccf6
- rules_apple:
- rules_swift:

## Additional context

<img width="1813" alt="Screen Shot 2022-10-28 at 12 23 29 PM" src="https://user-images.githubusercontent.com/62397110/198748627-85753a8c-855e-4115-a3f7-29aaec49df35.png">

**Comment by brentleyjones** [comment]
This is covered in the FAQ: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/docs/faq.md#when-i-build-i-get-warnings-like-stale-file-projectxcodeprojrules_xcodeprojgen_dir-is-located-outside-of-the-allowed-root-paths-how-do-i-fix-this. It should only happen once, and is recoverable.

**Comment by brentleyjones** [comment]
Let me know if that doesn't work for you, or if it happens more often than expected.
