### ISSUE TITLE
Bug: error of source code doesn't show in code editor window

### ISSUE THREAD

**Issue by tinder-kaijing** [buildbuddy-io/rules_xcodeproj#1378]
## Describe the bug

In code editor windows, to create an error of source code. For this case, to add a new undefined `AErrorProtocol_in_here` in the line #31, to expect to catch the error in code editor window of Xcode, but not.

## Reproduction steps
To use Xcode to open a generated project by using rules_xcodeproj, to create an error in code, and expect Xcode can catch the error. 

## Expected behavior
expect Xcode can catch the error in the code editor window.

## Versions
Bazel: 6.0.0-pre.20221020.1
rules_xcodeproj: 79ac13fdf7f2aeaafd9c6ce652cc564b621a80601955e34fed8ca3292630ccf6
rules_apple:
rules_swift:

## Additional context

<img width="1801" alt="Screen Shot 2022-10-28 at 12 57 23 PM" src="https://user-images.githubusercontent.com/62397110/198749968-b62e524f-6906-4fd9-8331-94aeaf81f30a.png">

**Comment by brentleyjones** [comment]
What does pressing the red error in the top right do? I haven't seen this behavior: errors in the bazel build log appear in the editor. You might have to send me the build log to see if it's somehow being formatted incorrectly, and thus not being picked up correctly.

**Comment by brentleyjones** [comment]
Also, does tapping the error in the navigator send you to the correct line?

**Comment by tinder-kaijing** [comment]
@brentleyjones Thanks for the prompt response. to click the error in the navigator does jump to the correct line. Only not see the error in code editor windows. suppose the error can ben cached early in editor window.

**Comment by tinder-kaijing** [comment]
> What does pressing the red error in the top right do? I haven't seen this behavior: errors in the bazel build log appear inline in the editor. You might have to send me the build log to see if it's somehow being formatted incorrectly, and thus not being picked up correctly.

Sure, I will send the build log to you via slack channel. Thanks again to look at this.

**Comment by brentleyjones** [comment]
This feels like an Xcode bug, but I would have to look at the Bazel log (a BuildBuddy invocation can help there) and the Xcode build report. You can send both to me in Slack (since it will include private info).
