### ISSUE TITLE
Bug: Unable to `po` using BwX

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#1386]
## Describe the bug

Using lldb commands, such as `po` results in an error

<img width="892" alt="CleanShot 2022-11-03 at 15 08 56@2x" src="https://user-images.githubusercontent.com/75236/199824078-7e21a469-1234-4b1d-8cb0-1adc7ba14c83.png">

## Reproduction steps

1. BwX
2. Set a breakpoint and break
3. Attempt to `po` any symbol

## Expected behavior

Prints the object

## Versions
- Bazel: 6.0
- rules_xcodeproj: 0.10.2
- rules_apple: 1.2.0
- rules_swift: 1.1.2

**Comment by brentleyjones** [comment]
I think I know what is wrong here. I'll look at it tomorrow.

**Comment by brentleyjones** [comment]
Can you:

- Set `log enable lldb types -f /tmp/lldb-types.log` in your `~/.lldbinit`
- Close Xcode
- Open it again
- Get to your breakpoint
- `po` and get the error
- Then send me that file in Slack?

I can't reproduce, so I need to see what is getting a messed up path. I thought it would be in `swift_debug_settings.py`, but that would only have this path in BwB mode. So it's instead Xcode's normal debug information, which should have valid paths for each module.

**Comment by brentleyjones** [comment]
@erikkerber are you able to reproduce this still?

**Comment by erikkerber** [comment]
Tested with a7cc6e1d

It still appears to reproduce. Sent logs.

<img width="878" alt="CleanShot 2023-01-05 at 15 00 13@2x" src="https://user-images.githubusercontent.com/75236/210879149-ae53609b-53a6-4358-8027-1bda45c2c0c1.png">
