### ISSUE TITLE
Feature Request: `associated_extra_files` for non_xcode_targets's

### ISSUE THREAD

**Issue by CognitiveDisson** [buildbuddy-io/rules_xcodeproj#1475]
Right now it's not possible to add `associated_extra_files` to objc_library without sources (headers only). If you try you will get an error:
```
 Are you using `alias`? For ``associated_extra_files`` it requires real target labels
```
It's sorta expected, since those targets can never become Xcode targets, so they are excluded from most logic paths, but it would be handy to be able to add non-compilable files associated with this target to the project.

**Comment by brentleyjones** [comment]
I'll probably start by making header-only library targets into Xcode targets. That will cover your main use case. It will be tricky to easily support other non_xcode_targets, like custom rules or codegen, so I'll have to think about that one.

**Comment by brentleyjones** [comment]
After #1494, is this still needed?

**Comment by CognitiveDisson** [comment]
It's been resolved by https://github.com/buildbuddy-io/rules_xcodeproj/pull/1494 . Thanks!
