### ISSUE TITLE
Bug: XcodeProjFilelist fails if xcodeproj  target name is too long

### ISSUE THREAD

**Issue by ra1028** [buildbuddy-io/rules_xcodeproj#1495]
## Describe the bug

[XcodeProjFilelist](https://github.com/buildbuddy-io/rules_xcodeproj/blob/ea8e26adbd79bbc09ddfbcddb58c24b201a24d2a/xcodeproj/internal/filelists.bzl) fails with code 36 (`cp` failure) if the target name of `xcodeproj` is too long.

## Additional context

Since rules_xcodeproj doesn't support multiple Xcode configurations as of now, we duplicate the xcodeproj target with different target names for each configuration.

```python
[
    xcodeproj(
        name = "xcodeproj-{0}-{1}-{2}-{3}".format(
            build_mode,
            ios_simulator_cpus,
            env,
            compilation,
        ),
        build_mode = build_mode,
        config = "rules_xcodeproj_{0}_{1}".format(env, compilation),
        ios_simulator_cpus = ios_simulator_cpus,
        ... 
    )
    for build_mode in [
        "bazel",
        "xcode",
    ]
    for ios_simulator_cpus in [
        "sim_arm64",
        "x86_64",
    ]
    for env in [
        "Dev",
        "Prod",
    ]
    for compilation in [
        "Debug",
        "Release",
    ]
]
```

The target names are quite long in this case to ensure their uniqueness, like `xcodeproj-bazel-sim_arm64-Dev-Debug`.
The `compilation` was added recently, but we noticed that build-cache warming has been failing on CI with the following error since it was added.
I haven't completely figured out the cause, but it seems that the too long target name was causing this problem.

```sh
//:xcodeproj-bazel-sim_arm64-Dev-Debug.generator
XcodeProjFilelist command exited with code 36
/bin/bash
-c
if [[ $OSTYPE == darwin* ]]; then cp -c "$1" "$2" else cp "$1" "$2" fi
bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-xxx/bin/xxx/xxx/xxx/xxx.indexstore
...
bazel-out/darwin-dbg/bin/xcodeproj-bazel-sim_arm64-Dev-Debug.generator-bi __xxx:xxx ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-xxx.filelist
```

## Reproduction steps

- Define xcodeproj target with name `xcodeproj-bazel-sim_arm64-Dev-Debug`.
- Run `bazel run //:xcodeproj-sim_arm64-Dev-Debug -- --generator_output_groups=all_targets 'build --remote_download_minimal'`

## Expected behavior

It works regardless of the length of the target name. 

## Versions
- Bazel: 6.0.0-pre.20220804.3
- rules_xcodeproj: 0.10.1
- rules_apple: d04edf4136b4818662d7126582ec257aee372339
- rules_swift: 6153a848f747e90248a8673869c49631f1323ff3
- Environment: CircleCI with BuildBuddy through RBE

**Comment by brentleyjones** [comment]
This should be fixed in `HEAD` by https://github.com/buildbuddy-io/rules_xcodeproj/commit/df9425a497a1b871885573cef2882d9dd75dcf11, can you confirm?

**Comment by ra1028** [comment]
I confirmed that it works with 0.11.0. Thanks for the fix!
