### ISSUE TITLE
Feature Request: Support `Arguments Passed On Launch` in `ios_unit_test` 

### ISSUE THREAD

**Issue by rasberik** [buildbuddy-io/rules_xcodeproj#1514]
Currently in `bazel test` it is possible to set something like `args = ["--command_line_args=-AppleLanguages,(en)"],` in order to pass `Arguments Passed On Launch` for test scheme. 
Expected Output would be: `-AppleLanguages (en)` (space separated)

It would be very useful to have same feature in `rules_xcodeproj` in order to achieve something like:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/103911733/209615520-3642215d-f8e1-49f8-a21a-bf8636defa13.png">

Regarding `--command_line_args`, it is [from here](https://github.com/bazelbuild/rules_apple/pull/1161).

**Comment by rasberik** [comment]
@brentleyjones Thank you! Let me know if I need to fill anything else

**Comment by ra1028** [comment]
Ref: https://github.com/bazelbuild/rules_apple/pull/1161
