### ISSUE TITLE
Bug: Breakpoints aren't resolved in iOS extensions in BwB mode

### ISSUE THREAD

**Issue by BalestraPatrick** [buildbuddy-io/rules_xcodeproj#1523]
## Describe the bug
When building with Bazel (BwB), breakpoints set in iOS extensions aren't resolved.

## Reproduction steps
I reproduced this in the `examples/integration` project as well as an internal project with various extensions (Widget and iMessage at least). You should be able to reproduce this by changing [this line](https://github.com/buildbuddy-io/rules_xcodeproj/blob/0c953d33d64a96ab61a7dfed546bbba6db9362df/examples/integration/BUILD#L50) to `bazel` and running `bazelisk run //:xcodeproj-sim_arm64` inside `examples/integration`. I set a breakpoint at `MessagesViewController:6` along with a `print("")` statement. When running the app in the Simulator, the breakpoint turns unresolved but the print statement works (meaning the app launched successfully).

## Expected behavior
Breakpoints should be resolved correctly and debugger should stop at breakpoints.

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 0c953d33d64a96ab61a7dfed546bbba6db9362df
- rules_apple: 2.0.0
- rules_swift: 1.5.0

## Additional context
As a more visual description, this is what the breakpoints look like after launching the iMessage app in the example project.

<img width="2168" alt="Screenshot 2023-01-04 at 10 49 57 PM" src="https://user-images.githubusercontent.com/3658887/210659423-270edb59-0b29-4ef0-97e5-014aa2416ab3.png">

**Comment by brentleyjones** [comment]
I think this is an issue specifically with iMessage and WidgetKit extensions (or at least this is the current issue I'm running into). Seems the way the schemes are currently created doesn't have allow debugging to be enabled. After I fix that I'll see if I can repro this.

**Comment by BalestraPatrick** [comment]
To be fair, I also reproduced this in a Notification extension IIRC.

**Comment by brentleyjones** [comment]
I think all of them have the same root issue with the scheme not being setup correctly for debugging.

**Comment by brentleyjones** [comment]
Ahh, so the issue actually seems to be that the .lldbinit isn't run for these extensions (which is why it's grayed out in the scheme UI). I found a way to get it applied, but now it's not working. Looking more.

**Comment by brentleyjones** [comment]
Hmm, it is being applied. I'm trying a different route of investigation now.

**Comment by brentleyjones** [comment]
Okay, so the custom `.lldbinit` isn't being run. But if I put the commands into `~/.lldbinit`, they are picked up, but breakpoints still don't resolve. I think it's because it launches a second debugging session for the extension process, and the changes aren't being applied correctly there.
