### ISSUE TITLE
Bug: rsync failure when running tests with BwB

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#1586]
## Describe the bug

When I run SwiftLint's tests in Xcode using BwB, I get rsync errors:

```
rsync: link_stat "/private/var/tmp/_bazel_jsimard/7034bb326caf3934edced22f6f4dd368/rules_xcodeproj/build_output_base/execroot/SwiftLint/bazel-out/darwin_arm64-dbg-ST-3182f29850cb/bin/Tests/SwiftLintFrameworkTests.xctest/Contents/MacOS/SwiftLintFrameworkTests.xctest" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/17b871cc-5535-11ed-b80b-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
```

Bisects to this commit: fb9555e2

The previous commit and version 0.10.1 don't exhibit this error.

## Reproduction steps

```console
git clone https://github.com/realm/SwiftLint
git checkout f8f2317bdbf0b402016036f577726403fd3bd58f
cd SwiftLint
bazel run xcodeproj
xed SwiftLint.xcodeproj
# cmd-U in Xcode
```

## Expected behavior

Tests should run.

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: fb9555e2 to `main` (0b9783519da870e13d8bae3876c7b7e82c29aac6)
- rules_apple: 2.0.0
- rules_swift: 1.5.0

## Additional context

Xcode build logs: [Build SwiftLint_2023-01-16T10-31-18.txt](https://github.com/buildbuddy-io/rules_xcodeproj/files/10427428/Build.SwiftLint_2023-01-16T10-31-18.txt)

![image](https://user-images.githubusercontent.com/474794/212719825-195eb40b-1668-487a-8c4e-5a348db69b7c.png)

**Comment by brentleyjones** [comment]
I'll get this fixed up tomorrow.

**Comment by brentleyjones** [comment]
I believe https://github.com/buildbuddy-io/rules_xcodeproj/commit/0ad6162d7c97e218d07c4892b864ceaaff150e5a is what actually broke it. Still looking into a fix.

**Comment by jpsim** [comment]
Thanks for the quick fix, I’ll let you know once I’ve had a chance to test it out.

**Comment by jpsim** [comment]
Confirmed fix. Thanks again.
