### ISSUE TITLE
Missing transitive dep with bzlmod

### ISSUE THREAD

**Issue by keith** [buildbuddy-io/rules_xcodeproj#1598]
## Describe the bug

```
ERROR: Internal precondition failure:
Target @SwiftLint//Tests:ExtraRulesTests was not found in the transitive dependencies of @//tools:swiftlint_xcodeproj's `top_level_targets` attribute. Did you reference an alias (only actual target labels are supported in Scheme definitions)? Check that @SwiftLint//Tests:ExtraRulesTests is spelled correctly, and if it is, add it or a target that depends on it to @//tools:swiftlint_xcodeproj's `top_level_targets` attribute.
Please file a bug report at https://github.com/buildbuddy-io/rules_xcodeproj/issues/new?template=bug.md
```

## Reproduction steps

We use SwiftLint's bazel feature to add extra rules and then generate this project for working on those extra rules:

```bzl
xcodeproj(
    name = "swiftlint_xcodeproj",
    bazel_path = "./bazelw",
    project_name = "SwiftLint",
    schemes = [
        xcode_schemes.scheme(
            name = "SwiftLint",
            build_action = xcode_schemes.build_action(
                targets = [
                    "@SwiftLint//:swiftlint",
                ],
            ),
            launch_action = xcode_schemes.launch_action(
                "@SwiftLint//:swiftlint",
                args = [
                    "--progress",
                ],
            ),
            test_action = xcode_schemes.test_action([
                "@SwiftLint//Tests:ExtraRulesTests",
            ]),
        ),
    ],
    tags = ["manual"],
    top_level_targets = [
        "@SwiftLint//:swiftlint",
        "@SwiftLint//Tests:ExtraRulesTests",
    ],
)
```

When switching to bzlmod for swiftlint + rules_xcodeproj we hit the error above

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 0.12.0
- rules_apple: 2.0.0
- rules_swift: 1.5.1

## Additional context

This requires https://github.com/realm/SwiftLint/pull/4704 and some other bzlmod deps right now, might be easier to test later

**Comment by keith** [comment]
[repro.zip](https://github.com/buildbuddy-io/rules_xcodeproj/files/10451347/repro.zip)

here's a repro case

**Comment by brentleyjones** [comment]
I think we are currently blocked on https://github.com/bazelbuild/bazel/issues/17260 when the labels reference external repos.

**Comment by brentleyjones** [comment]
Looks like we might get a fix in 6.1.

**Comment by brentleyjones** [comment]
We won't delay the release over this change. We will fix it whenever the change in Bazel lands.

**Comment by brentleyjones** [comment]
We can fix this with 6.1: https://github.com/bazelbuild/bazel/commit/c540ebf58e16687442700d03f2566b0dc0b85907

**Comment by keith** [comment]
is it possible to fix now with that having landed using `getattr` for backwards compat?

**Comment by brentleyjones** [comment]
Ahh, yes. I'll get to it early next week.
