### ISSUE TITLE
Bug: Strict Concurrency Checking Unavailable in Fresh Project (BwB Mode)

### ISSUE THREAD

**Issue by tinder-cwybranowski** [buildbuddy-io/rules_xcodeproj#1657]
## Describe the bug

The Xcode 14+ / Swift 5.7 `Strict Concurrency Checking` build setting does not surface concurrency compilation warnings when built via a `rules_xcodeproj`-generated Xcode project in BwB mode. 

## Reproduction steps

I've created a [demo repository](https://github.com/tinder-cwybranowski/xcode-strict-concurrency-checking-demo) that contains the following lanes to compare expected behavior:

- Vanilla Xcode (powered by XcodeGen Xcode project)
- rules_xcodeproj BwB
- rules_xcodeproj BwX

**Note:** If there's a way to codify the injection of the `Strict Concurrency Checking` build setting (`SWIFT_STRICT_CONCURRENCY` in an actual project file) into the `xcodeproj` targets themselves, I'm happy to update the repro steps to reduce the required manual configuration.

## Expected behavior

Two concurrency compilation warnings are surfaced during the `SwiftLib` build.

## Versions
- Bazel: [6.0.0](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo/blob/main/.bazelversion#L1)
- rules_xcodeproj: [0.12.0](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo/blob/main/WORKSPACE#L6)
- rules_apple: 2.0.0 ([transitively via `rules_xcodeproj`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/0.12.0/xcodeproj/repositories.bzl#L90))
- rules_swift: 1.5.1 ([transitively via `rules_xcodeproj`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/0.12.0/xcodeproj/repositories.bzl#L83))

## Additional context

- [`Strict Concurrency Checking: complete` build setting works as expected in BwX mode](https://github.com/tinder-cwybranowski/xcode-strict-concurrency-checking-demo#expected-outcome)

**Comment by tinder-cwybranowski** [comment]
> Does your `bazel build` version of the project have strict concurrency enabled? If so, the flag that Bazel uses should be coming through to in `SWIFT_FLAGS` (so we wouldn't need `SWIFT_STRICT_CONCURRENCY`).
> 
> I see in your repo that you modify the build settings in Xcode. That won't impact a BwB project, and can actually lead to indexing errors. If you need to modify a flag, it needs to come from a Bazel set copt.

That would be the problem 🤦 Apologies for the alarm!

After adding `-warn-concurrency` to the `copts` of `SwiftLib`, I see the compiler warnings when building on command-line (via `bazelisk build //src:SwiftLib`):
```
    copts = [
        "-warn-concurrency"
    ],
```

However, those same warnings still do not surface in the BwB project, despite this edit. Any guidance on how to propagate this `copt` to the BwB build would be greatly appreciated.

**Comment by brentleyjones** [comment]
It should come through. Can you update your repro and let me know, and then I can look at it. Are you not seeing it in `SWIFT_FLAGS`?

**Comment by tinder-cwybranowski** [comment]
> It should come through. Can you update your repro and let me know, and then I can look at it. Are you not seeing it in `SWIFT_FLAGS`?

[Just pushed the latest revision](https://github.com/tinder-cwybranowski/xcode-strict-concurrency-checking-demo/commit/b14958703e98466a111b3ff198a5a2b879a575f8). It seems like it may have been a cached build that was hiding the compiler warnings (I originally built via Bazel on command-line, so without any additional source impacts, it didn't re-surface any warnings -- similar to the behavior of repeated command-line builds).

I just confirmed that impacting the original source file + triggering a rebuild in a BwB project does in fact surface the concurrency compiler warnings as expected.

Separately, where can I inspect the value of `SWIFT_FLAGS`? Would be great to know how to troubleshoot this in the future.

**Comment by brentleyjones** [comment]
Sorry, the Xcode build setting is `OTHER_SWIFT_FLAGS`.

**Comment by tinder-cwybranowski** [comment]
> Sorry, the Xcode build setting is `OTHER_SWIFT_FLAGS`.

Ah yes, I can see the propagated copt in `OTHER_SWIFT_FLAGS`:

<img width="800" alt="Screenshot 2023-01-25 at 3 38 42 PM" src="https://user-images.githubusercontent.com/40372184/214685171-5cc88ebc-7cb6-41c6-8d83-f94b3fd69a9a.png">

Thanks again for your help, this was a good learning for me 😄
