### ISSUE TITLE
Bug: Copy with clonefile fails when output_base and workspace are on different volumes

### ISSUE THREAD

**Issue by arrizer** [buildbuddy-io/rules_xcodeproj#1746]
## Describe the bug
When setting the bazel `output_base` to a different volume than the one where the workspace to build resides, a couple of operations using `cp -c` fail with `clonefile failed: Cross-device link`. This happens for example when using a RAM disk as output_base, which is a different volume.

Removing the `-c` flag from the following locations fixes the issue:
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/bazel_integration_files/BUILD#L100
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/filelists.bzl#L19
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/installer.template.sh#L141
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/installer.template.sh#L147
https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/product.bzl#L40

To not lose the advantages of using clonefile, a proper fix would be to check if source and destination reside on the same volume to decide whether or not to use `-c`.  Something along the lines of

```
if [[ $(stat -f '%d' "$from") == $(stat -f '%d' "$to") ]]; then
```

## Reproduction steps
1. Set `output_base` to a different volume than the current workspace
2. Generate project (BwB mode)
3. Build and run in Xcode

## Expected behavior
Copying across volumes should work without errors

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 1.0.0

**Comment by arrizer** [comment]
@brentleyjones I ran into one issue now, after running a `bazel clean--expunge` that did not show up before:
```
ERROR: /xxxxx/BUILD.bazel:30:20: Generating bazel-out/applebin_ios-ios_sim_arm64-dbg-ST-704045b513f2/bin/xxxxxxx.filelist failed: (Exit 1): bash failed: error executing command
  (cd /Volumes/RamDisk/bazel/rules_xcodeproj/build_output_base/execroot/xxx && \
  exec env - \
  /bin/bash -c 'if [[ $(stat -f '\''%d'\'' "$1") == $(stat -f '\''%d'\'' "${2%/*}") ]]; then
  cp -c "$1" "$2"
else
  cp "$1" "$2"
fi
' ''
```
Could not find any more details, other than `bash failed: error executing command`. Seems to be related to this change: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/filelists.bzl#L19
The other invocations did not cause issues.

**Comment by brentleyjones** [comment]
:+1: I'll get a fix in

**Comment by brentleyjones** [comment]
Seems the issue was that the volume was HFS+ instead of APFS. Currently we only support APFS volumes.
