### ISSUE TITLE
Feature Request: Add support for `usesTabs`/`indentWidth`/`tabWidth` Xcode options

### ISSUE THREAD

**Issue by mattrobmattrob** [buildbuddy-io/rules_xcodeproj#1753]
I quickly looked at the XcodeProj codebase and unfortunately it looks annoyingly difficult to use in relation to setting a project level indent value ([unlike XcodeGen root `options` value](https://github.com/bazel-ios/rules_ios/blob/142f36e3719c0c9191ae7114a18eaaba9503832b/rules/legacy_xcodeproj.bzl#L472-L496)). This might already be supported somehow but I couldn't find it.

https://github.com/tuist/XcodeProj/blob/13705282e17ab2955790a204827f8827068a79f2/Sources/XcodeProj/Objects/Files/PBXFileElement.swift#L114-L122

We define this like this for our project:
```Starlark
xcodeproj_project_options(
    name = "xcodeproj_options",
    indent_width = 2,
    tab_width = 2,
    uses_tabs = False,
)
```

**Comment by mattrobmattrob** [comment]
This, for example, creates the proper settings in the project, from what I can tell:
```diff
diff --git a/tools/generator/src/Generator/CreateProject.swift b/tools/generator/src/Generator/CreateProject.swift
index 270e3363..c64c63e6 100644
--- a/tools/generator/src/Generator/CreateProject.swift
+++ b/tools/generator/src/Generator/CreateProject.swift
@@ -37,7 +37,10 @@ extension Generator {

         let mainGroup = PBXGroup(
             sourceTree: forFixtures ? .group : .absolute,
-            path: srcRoot
+            path: srcRoot,
+            usesTabs: false,
+            indentWidth: 2,
+            tabWidth: 2
         )
         pbxProj.add(object: mainGroup)
```

Any suggestions on your preferred input pattern to get it here, @brentleyjones? How about a JSON file passed into `ctx.attr._generator` args similar to `xccurrentversions_file`?

**Comment by brentleyjones** [comment]
I would expect this to come over in the project spec. The main question I have is what the rule API will look like.

**Comment by mattrobmattrob** [comment]
I did a simple wrapper for a provider before, not sure if you'd want a similar thing for "project options" or similar.

https://github.com/bazel-ios/rules_ios/blob/142f36e3719c0c9191ae7114a18eaaba9503832b/rules/legacy_xcodeproj.bzl#L472-L496

**Comment by brentleyjones** [comment]
I'll write up an ideal API tomorrow. I think we can get away without adding any additional rules.
