### ISSUE TITLE
Bug: The apple_xcframework rule does not yet support the experimental tree artifact.

### ISSUE THREAD

**Issue by AttilaTheFun** [buildbuddy-io/rules_xcodeproj#1766]
## Describe the bug

I'm trying to build an apple_xcframework from a swift_library and generate an Xcodeproj from that with rules_xcodeproj and I'm getting this error:

```
logan@Logans-MBP Snag % bazel run //Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIXcodeproj
INFO: Build options --compilation_mode, --define, and --features have changed, discarding analysis cache.
INFO: Analyzed target //Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIXcodeproj (5 packages loaded, 13 targets configured).
INFO: Found 1 target...
Target //Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIXcodeproj up-to-date:
  .bazel/bin/Libraries/FoundationUI/ViewFoundationUI/ViewFoundationUIXcodeproj-runner.sh
INFO: Elapsed time: 0.134s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: .bazel/bin/Libraries/FoundationUI/ViewFoundationUI/ViewFoundationUIXcodeproj-runner.sh

Generating "ViewFoundationUI.xcodeproj"
INFO: Build options --compilation_mode, --define, and --features have changed, discarding analysis cache.
ERROR: /Users/logan/Developer/Swift/Apps/Snag/Libraries/FoundationUI/ViewFoundationUI/BUILD:18:18: in apple_xcframework rule //Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIFramework: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_logan/9c5dc880d421e060978209038345ac60/external/build_bazel_rules_apple/apple/internal/xcframework_rules.bzl", line 466, column 13, in _apple_xcframework_impl
                fail("The apple_xcframework rule does not yet support the experimental tree artifact. " +
Error in fail: The apple_xcframework rule does not yet support the experimental tree artifact. Please ensure that the `apple.experimental.tree_artifact_outputs` variable is not set to 1 on the command line or in your active build configuration.
ERROR: /Users/logan/Developer/Swift/Apps/Snag/Libraries/FoundationUI/ViewFoundationUI/BUILD:18:18: Analysis of target '//Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIFramework' failed
ERROR: Analysis of target '//Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIXcodeproj.generator' failed; build aborted: 
INFO: Elapsed time: 0.373s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (92 packages loaded, 3225 targets configured)
ERROR: Build failed. Not running target
```

I tried passing the flag it mentioned with `bazel run --define apple.experimental.tree_artifact_outputs=0 //Libraries/FoundationUI/ViewFoundationUI:ViewFoundationUIXcodeproj` but this had no effect.

## Reproduction steps

My rules are defined like so:

```
load("@build_bazel_rules_apple//apple:apple.bzl", "apple_xcframework")

apple_xcframework(
    name = "ViewFoundationUIFramework",
    bundle_id = "com.LoganShire.ViewFoundationUIFramework",
    families_required = {
        "ios": [
            "iphone",
            "ipad",
        ],
    },
    infoplists = [":Info.plist"],
    minimum_os_versions = {
        "ios" : "14.0",
    },
    visibility = ["//visibility:public"],
    deps = [
        ":ViewFoundationUI",
    ],
)

load(
    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:defs.bzl",
    "top_level_target",
    "xcodeproj",
)

xcodeproj(
    name = "ViewFoundationUIXcodeproj",
    project_name = "ViewFoundationUI",
    tags = ["manual"],
    top_level_targets = [
        top_level_target(":ViewFoundationUIFramework", target_environments = ["simulator"]),
    ],
)
```

Where ViewFoundationUI is a swift_library which just has a empty swift file right now.

## Expected behavior

Because rules_xcodeproj supports apple_xcframework as a top-level target, I expect it should be able to generate an Xcodeproj for it.

## Versions

logan@Logans-MBP Snag % bazel version
Bazelisk version: development
Build label: 6.0.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:52:58 2022 (1671465178)
Build timestamp: 1671465178
Build timestamp as int: 1671465178

http_archive(
    name = "com_github_buildbuddy_io_rules_xcodeproj",
    sha256 = "cb4ae95d86a1961734f17a1d4743010480a576214519ceb2ce9cec34b88da7b2",
    strip_prefix = "rules_xcodeproj-0bad4f33c462f5a26e4c13861afd181e56729938",
    url = "https://github.com/buildbuddy-io/rules_xcodeproj/archive/0bad4f33c462f5a26e4c13861afd181e56729938.tar.gz",
)

http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "43737f28a578d8d8d7ab7df2fb80225a6b23b9af9655fcdc66ae38eb2abcf2ed",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/2.0.0/rules_apple.2.0.0.tar.gz",
)

**Comment by brentleyjones** [comment]
We haven't made an effort to support this rule yet. It's still on the roadmap: https://github.com/buildbuddy-io/rules_xcodeproj/issues/107.

**Comment by AttilaTheFun** [comment]
Ah okay, I subscribed to the ticket. Maybe the error should just say that apple_xcframework isn't supported yet as that would be clearer.

**Comment by brentleyjones** [comment]
I would use ios_framework for now. The xcframework target is for distribution (making an artifact to send to others). I'm not sure if you are trying to do that, but if you just want to use it in your own workspace, you should use the other rules.

That's the main reason we haven't prioritized them yet, since the Xcode experience is mainly about running and debugging your own stuff. If you need something for distribution you can build those targets on the bazel command line (and you should, since we don't support the Archive action).

**Comment by louwers** [comment]
I am not sure what I should use as a top-level target otherwise, since `objc_library` cannot be used as a top-level target either. I guess I should build an app with Bazel as well.

https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/BUILD.bazel#L103
