### ISSUE TITLE
Bug: Missing simulator? 

### ISSUE THREAD

**Issue by louwers** [buildbuddy-io/rules_xcodeproj#1768]
## Describe the bug

I am trying to generate a `xcodeproj` from a `ios_framework`. However, I am not having any success with it due to this error:

> Error: key "//platform/ios:sdk ios-sim_arm64-min9.0-applebin_ios-ios_sim_arm64-dbg-ST-c5749babf614" not found in dictionary

It looks like it can't find some simulator (for iOS 9.0) but when I bump the version number of my `ios_framework` it still fails for the same reason. Since I did not see any information about simulators in the documentation I would like to better understand this error.

```
Generating "MapLibre-Native.xcodeproj"
ERROR: /Users/bart/src/maplibre-gl-native/platform/ios/BUILD.bazel:367:10: in bwb_xcodeproj rule //platform/ios:xcodeproj.generator: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_bart/47d11f9a9b5330b4824e32638a4f4218/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 1380, column 25, in _xcodeproj_impl
                ) = _process_targets(
        File "/private/var/tmp/_bazel_bart/47d11f9a9b5330b4824e32638a4f4218/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 504, column 37, in _process_targets
                src_target = focused_targets[src]
Error: key "//platform/ios:sdk ios-sim_arm64-min9.0-applebin_ios-ios_sim_arm64-dbg-ST-c5749babf614" not found in dictionary
ERROR: /Users/bart/src/maplibre-gl-native/platform/ios/BUILD.bazel:367:10: Analysis of target '//platform/ios:xcodeproj.generator' failed
ERROR: Analysis of target '//platform/ios:xcodeproj.generator' failed; build aborted: 
INFO: Elapsed time: 0.072s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

## Reproduction steps

```
git clone git@github.com:louwers/maplibre-gl-native.git
cd maplibre-gl-native
git checkout ios-xcode-bazel
git submodule update --init --recursive
bazel run //platform/ios:xcodeproj 
```

In the repo below:

https://github.com/louwers/maplibre-gl-native/blob/ios-xcode-bazel/platform/ios/BUILD.bazel#L367

## Expected behavior

xcodeproj generated

## Versions
- Bazel: 6.0.0-pre.20220630.1
- rules_xcodeproj: 1.1.0
- rules_apple: 76752fe84ff0dc5d793033015647c78efbf41309
- rules_swift: N/A

**Comment by brentleyjones** [comment]
Thanks for the reproduction!

There isn't really anything to understand with the error, it was a logic error in the Starlark. I have a PR that will land soon that fixes this specific issue. Then the project runs into https://github.com/bazelbuild/rules_swift/issues/907, which will require a rules_swift release (which should be today, and I'll get that into a new rules_xcodeproj release along with this fix).

Finally, I recommend updating to Bazel 6. The repo is using a pre-release version that is really old. And you can remove the custom loading of rules_apple and use the one that rules_xcodeproj pins to, if you want.

**Comment by louwers** [comment]
@brentleyjones I actually updated Bazel locally (but did not push it yet).

Happy you could find the issue! Thanks for looking into it.
