### ISSUE TITLE
Bug: Focused rules_ios targets do not show headers in Xcode

### ISSUE THREAD

**Issue by yongjincho92** [buildbuddy-io/rules_xcodeproj#1774]
## Describe the bug
When using focused_targets functionality on rules_ios targets, the header of the rules_ios targets are not visible from Xcode app.

## Reproduction steps
1. Download and extract the zip file [Repro.zip](https://github.com/buildbuddy-io/rules_xcodeproj/files/10797932/Repro.zip)
2. `bazel run //:App.xcodeproj` and check that headers are all visible from Xcode 
3. `bazel run //:FocusedApp.xcodeproj` and check that headers of focused target is not visible from Xcode 

## Expected behavior
Headers of focused target is visible from Xcode 

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 1.1.0 
- rules_apple: transitively pulled in https://github.com/bazel-ios/rules_ios/blob/master/rules/repositories.bzl
- rules_swift: transitively pulled in https://github.com/bazel-ios/rules_ios/blob/master/rules/repositories.bzl

## Additional context
This issue doesn't occur to targets that do not use rules_ios rules. (simple rules_apple targets seem to work fine).

**Comment by brentleyjones** [comment]
Sorry, but the repro doesn't have any source files, so it doesn't build correctly. For example, `FW`, `FW2`, and `Libraries` are all empty.

**Comment by yongjincho92** [comment]
Updated repro.zip 
[Repro.zip](https://github.com/buildbuddy-io/rules_xcodeproj/files/10807105/Repro.zip)

**Comment by brentleyjones** [comment]
Thanks for the repro! The fix will be in the next release.

**Comment by yongjincho92** [comment]
@brentleyjones I see that you've merged the fix into 1.2.0. However, I think the issue is still there even on 1.2.0.

**Comment by brentleyjones** [comment]
Do you reproduce it with the same repro? That was what I checked against and it was fixed.

**Comment by brentleyjones** [comment]
Actually, this isn't in 1.2.0, it will be in the _next_ release. Please test `main` in the meantime.
