### ISSUE TITLE
Bug: ios_framework with exported_symbol_lists fails to build in BwX mode

### ISSUE THREAD

**Issue by gferon** [buildbuddy-io/rules_xcodeproj#1779]
## Describe the bug

When using a `ios_framework` with a generated `exported_symbols_list` (using `genrule`), the project doesn't build in Xcode because the file is missing. I'm not sure where to get started to start looking into this.

## Reproduction steps

* Use https://github.com/buildbuddy-io/rules_xcodeproj/compare/main...gferon:rules_xcodeproj:repro-symbols-list
* `bazel run //:xcodeproj-sim_arm64`
* Try to build `LibFramework` in Xcode

## Expected behavior

* This should work 😅 

## Versions
- Bazel: 6.0
- rules_xcodeproj: 1.1.0
- rules_apple: `8686b2bf081e94f87da2d0238abbe728bff421a31d0fa666a63662facec52005`

**Comment by brentleyjones** [comment]
Thank you for the reproduction! I've fixed it in #1780.

**Comment by brentleyjones** [comment]
Btw, I just release 1.2.0, which includes this fix.

**Comment by gferon** [comment]
Wow, that was insanely quick, thanks a lot!
