### ISSUE TITLE
Ensure that the Bazel symlinks are not created for child workspaces.

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#181]
This avoids errors when attempting to build/test from the parent workspace.

**Comment by cgrindel** [comment]
This is on hold per [this discussion](https://github.com/buildbuddy-io/rules_xcodeproj/pull/194#pullrequestreview-917922422).

**Comment by brentleyjones** [comment]
Resolved with #1014.
