### ISSUE TITLE
Bug: Project can fail to build if the `.xcodeproj` file is renamed

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#202]
## Describe the bug

If the project uses internal rules_xcodeproj files, which will almost always be the be the case (e.g. uses generated files, compile stub, etc.), those paths are hardcoded to include the path to the `.xcodeproj` file. So if the project file is renamed, the build can fail.

## Expected behavior

We can probably get around this by creating a Run Script target that generates these files into Derived Data instead of creating them at project generation, and reference those in the project instead. I'm not 100% sure on that though, as `BUILT_PRODUCTS_DIR` is currently set differently for each target. Maybe we can get that back to a stable location, while still having targets produced into the `bazel-out/`-like directory structure.

If we can't fix this to "just work", we can have the build fail in a predictable way similar to one of the suggested fixes to #201. If `PROJECT_FILE_PATH` is different than expected we can require a regeneration of the project.

**Comment by erikkerber** [comment]
I’m not sure of all the failure modes you’re trying to avoid, but I believe both rules_ios and Tulsi install these files into the Xcode project directory themselves (i.e. `My.xcodeproj/.bazel`). At least things like stubs, and are easily referenced with `PROJECT_DIR`

**Comment by brentleyjones** [comment]
That's where they are now. There wasn't a `PBXSourceTree` that allowed me to easily reference them with `PBXFileReference`. I'll check to see if I missed one though.

**Comment by brentleyjones** [comment]
So this is super interesting. If I use `PBXSourceTree.custom("PROJECT_FILE_PATH")`, the project navigator doesn't work (all the files are always red), but the project still compiles correctly. This is probably because `PROJECT_FILE_PATH` isn't set yet for the navigator, but by the time the build system gets to resolving the `PBXFileReference`, it is set.

Only the compile stub needs to be a `PBXFileReference`. The rest I can just reference via `PROJECT_FILE_PATH` regardless.

If I could find a way to have a `PBXFileReference` without it showing in the navigator, that would be best. Otherwise I think generating the compiler stub to `BUILT_PRODUCTS_DIR`, while leaving the rest in place, but no longer in the project navigator, is the best path forward.

**Comment by brentleyjones** [comment]
I'm thinking the best we will be able to do for this is detect it in `BazelDependencies`, comparing the hardcoded value used in the Project navigator to `PROJECT_FILE_PATH` and bailing early. As it stands, any renamed projects with external dependencies or generated files will fail to build.

**Comment by brentleyjones** [comment]
With https://github.com/buildbuddy-io/rules_xcodeproj/pull/880 and https://github.com/buildbuddy-io/rules_xcodeproj/commit/b79ee534a94eedf8d32c1fe4a3c6008650ee1e4b, we no longer have the project file path referenced directly.
