### ISSUE TITLE
Provide API documentation

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#214]
We should use [stardoc](https://github.com/bazelbuild/stardoc) to generate API documentation for the rules.

**Comment by brentleyjones** [comment]
@BalestraPatrick @jpsim How valuable do you think it would be to add developer documentation for the generator, using DocC?

**Comment by jpsim** [comment]
> How valuable do you think it would be to add developer documentation for the generator, using DocC?

Probably not hugely beneficial since the generator is only meant to be used by rules_xcodeproj, and not broadly by external consumers.

**Comment by brentleyjones** [comment]
I think this is done. We can continue to improve the documentation we have now, but we do have it being generated.
