### ISSUE TITLE
Feature Request: Support bzlmod

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#248]

**Comment by brentleyjones** [comment]
@BalestraPatrick You have some experience with this. I assume we are blocked until rules_swift supports bzlmod?

**Comment by BalestraPatrick** [comment]
Yes, only `apple_support` supports bzlmod at the moment. Do you know if we would need to do anything specific from our side?

**Comment by brentleyjones** [comment]
I haven't touched anything related to bzlmod yet 😬.

**Comment by brentleyjones** [comment]
This is done at the basic level. Still needs https://github.com/buildbuddy-io/rules_xcodeproj/issues/1598 for full support.
