### ISSUE TITLE
Bug: `ENABLE_TESTING_SEARCH_PATHS` build setting not set when `testonly = True`

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#256]
Xcode provides `ENABLE_TESTING_SEARCH_PATHS` which will include `Developer/Library/Frameworks` to the builds search paths, so developers can use XCTest libraries in non-test targets.

Currently rules_swift [sets that for everything](https://github.com/bazelbuild/rules_swift/commit/768bfe3fe885f92fbaea75488268e2612ab9ef9c#diff-b66f80b469020168d63d1079602ed95b2dd607240c182a4a1098b34eb865020eR157), while Xcode makes it disabled-by-default.

**Comment by brentleyjones** [comment]
Looks like it is only set when test_only is set: https://github.com/bazelbuild/rules_swift/commit/768bfe3fe885f92fbaea75488268e2612ab9ef9c#diff-b66f80b469020168d63d1079602ed95b2dd607240c182a4a1098b34eb865020eR267

**Comment by brentleyjones** [comment]
So we have code to do this, and it's working for test targets. I wonder where it's failing for other targets? Do you have more details @erikkerber?

https://github.com/buildbuddy-io/rules_xcodeproj/blob/0e2b21635c7b2752940261d37c34b22e7a68348a/xcodeproj/internal/target.bzl#L734-L738

**Comment by erikkerber** [comment]
We did *not* have `testonly` applied to these targets before today, and I'll re-test.

They are testing helper targets that utilize XCTest, but not test targets themselves.

**Comment by brentleyjones** [comment]
Given https://github.com/bazelbuild/rules_swift/commit/768bfe3fe885f92fbaea75488268e2612ab9ef9c#diff-b66f80b469020168d63d1079602ed95b2dd607240c182a4a1098b34eb865020eR267, how did they link correctly with Bazel?

**Comment by erikkerber** [comment]
I tested this and it does work if targets are applied with `testonly = True`

Closing 👍🏼

**Comment by erikkerber** [comment]
Yes. My read in rules_swift, and I could be wrong, is that `Developer/Library/Frameworks` is added unconditionally.

**Comment by brentleyjones** [comment]
That seems like a bug to me. Someone should fix it 😉.

**Comment by brentleyjones** [comment]
Re-opening, as we need to change to mimic rules_swift, or (ideally) rules_swift needs to adjust to only add the framework search paths for `test_only = True`.

**Comment by maxwellE** [comment]
Created [this pr](https://github.com/bazelbuild/rules_swift/pull/839) in rules_swift

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/rules_swift/pull/840 should address this from the rules_swift side.

**Comment by brentleyjones** [comment]
After we update to a released version with the fix.

**Comment by maxwellE** [comment]
Should we point at a new sha for [Xcod](https://github.com/tuist/XcodeProj or push on them to make a new release?
