### ISSUE TITLE
Add detailed feature list to README

### ISSUE THREAD

**Issue by cpsauer** [buildbuddy-io/rules_xcodeproj#283]
Hey build buddy folks,

Looks like a neat new tool you're working on here! For those of us who already use, e.g., Tulsi (or XCHammer) and would consider switching, could I ask how it compares--in goals and status--to the previous Xcode<>Bazel efforts? 

[Sorry if I've such a comparison already exists and I've missed it somewhere.]

I'm also going to tag @BalestraPatrick and @erikkerber -- since from the release notes it sounds like they've been switching over and playing around with it on their codebases!

Thanks so much!
Chris

**Comment by brentleyjones** [comment]
It's on my TODO list to make a comparison to Tulsi, rules_ios, and XCHammer, along with a design/vision document

 In the meantime, this Twitter thread, and the blog post I link to at the start, should be a good holdover: https://twitter.com/brentleyjones/status/1512137776782794753.

**Comment by cpsauer** [comment]
Sweet! Thanks for replying so fast. Good luck and thanks @brentleyjones. Have really enjoyed your 👍🏻s and interacting with you around the GitHub bazel verse, btw. Also, I **_love_** the logo :) Have showed several people just for that.

[Super helpful, btw. Can't use right now, I think, because I'm pretty sure I need the actual build to be in Bazel. But I remain very excited.]

**Comment by brentleyjones** [comment]
@cpsauer FYI, we added a high level design goals document: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/doc/design/high-level.md.

Thinking more on this, I don't think it would be in good taste to create a document that does a direct comparison to any of the other generators. I think it would instead be best to celebrate all of the things that this generator does well. The README has a small section on this already, but because it's before 1.0, it's a little lite. If that was beefed up, would that be good enough in your eyes? If not, what could we do without directly comparing to other projects?

**Comment by cpsauer** [comment]
Thanks, Brentley! You're great :)

That linked doc especially helps my understanding of how things are evolving around build modes (building with Xcode vs Bazel vs proxy), and the goals behind each mode. Some of my main (implicit) questions were around better understanding those build modes and feeling reassured about being able to produce outputs consistent with Bazel even with custom rules (and select()s) up the dependency chain. 

The hybrid build parts also really got me thinking about which parts of my build I really need/want to be in Bazel vs Xcode. An interesting question! I know I want to specify platform-independent build info in Bazel; I think we're mostly interested in using Bazel for sharing code across platforms. If the Apple-specific outer wrappings, build targets, and tests were done via Xcode, even as their source of truth, calling into Bazel to build their (configured) cross-platform dependencies, that'd be an interesting paradigm shift, and as you say, great for supporting new features Apple has just released that are hard to wrap in Bazel. I don't know how universal that attitude is--maybe lots of people want Bazel to build their Apple-specific code--and I certainly need to think more, but it strikes me that you've hit on something very interesting with hybrid building.

I totally get (and love!) the goodheartedness in not wanting to do direct comparisons and to value everyone's good efforts. I do think, though, that your users will probably be implicitly comparing in deciding which to use. It'd be easy to assume they know more about the differences than they do, and I think comparisons, even implicitly, would really help them make good decisions per unit of evaluation effort. I'd still encourage directly (but respectfully) explaining how this project is different and better--whenever you're ready for that 1.0 launch and feel ready for people to make that comparison. But as you say, maybe the best way to do that--maximally respectfully and without naming names--would be to specially celebrate the the important use cases this tool enables. That is, to highlight the special ways this tool supports you (and implicitly that the other tools do not). That'd really help people make decisions, I think! Even just saying that you'd recommend people use this tool for their Apple editing needs would go a long way, I bet--whenever you're ready to launch, of course. My 2c anyway :) And I totally agree that the README is a great place for that.

Cheers! And thanks for all you do.
Chris

**Comment by brentleyjones** [comment]
Status update:

- We are now on https://bazel.build/install/ide
- The README extensively lists features. In particular:
  - Comprehensive Xcode feature support
  - Comprehensive rules coverage
  - BwX mode (though it's not what we recommend you use)
- "Projects using" as a indirect way for them to endorse the project
- BazelCon video showing off the features and ease of use

@cpsauer Could you give this all a fresh look to see what we might be missing. I still don't want to do direct comparisons, and I understand how I might be underselling how great the generator is by doing that. So far I've just asked people to try it, which is usually enough to get them to convert. Given all of that though, maybe there is more we can do?

**Comment by brentleyjones** [comment]
Related: we should get https://github.com/bazelbuild/bazel/blob/master/site/en/migrate/xcode.md updated since it only mentions Tulsi.

**Comment by brentleyjones** [comment]
Someone offline probably convinced me that I should still do a comparison, but not host it in this repo (so probably my personal blog instead). I might eventually do that.

Closing this for now, as I have it tracking the 1.0 release. I'll open it again if anyone has further changes they feel we should make.

**Comment by cpsauer** [comment]
Hey, Brently! I've been off in [cross-platform VSCode land](https://github.com/hedronvision/bazel-compile-commands-extractor) for a bit, and thus out of the loop, but seeing your 1.0 launch--and this--put a big smile on my face. Huge congratulations on all you've done here (and elsewhere).

+1 for the migrate doc, but I assume you're tracking that elsewhere.

I still really do think you could help save new users evaluation time--who might otherwise just start with the tool with the most stars--by making it super clear which "key differentiated features" this adds in the README. (Or something like that. Idea radiation: Key differentiated features could be bold with a legend at the bottom?) I know I've already probably pushed for comparison too much already, but that seems like a tasteful alternative and I know I'd have really valued that upon first finding this, and I bet others would, too.

Looking forward to diving in more the next time I'm in Xcode land! And reading that blog post if and when you post it.

Good luck! Cheering for you.
Chris

**Comment by brentleyjones** [comment]
I like the "key differentiated features" idea. I'll probably run with that soon.

**Comment by cpsauer** [comment]
Heh, I'd say https://github.com/bazelbuild/tulsi/pull/400 pretty well resolves this need.

**Comment by brentleyjones** [comment]
There are still a couple of other less known options, so I still plan to tweak the docs a bit more based on your most recent feedback. But yes, that should help a bit 😅.
