### ISSUE TITLE
Add FAQ for common questions

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#295]
Initial questions:
- My Xcode project seems to be out of sync. What should I do?
- How can I ensure that Bazel generated files are sync'd properly with my Xcode project?

**Comment by jszumski** [comment]
I think it'd be great to cover that stdout/stderr doesn't get replayed for cache hits.  Maybe "Why do warnings seem to disappear randomly from Xcode?"

**Comment by brentleyjones** [comment]
Well, we currently don't have Build with Bazel, and when we do, my goal is to _not_ have then disappear (including for cache hits).

But yes, if that was the case, we should have that in there. Basically any behaviors that differ from a "normal" Xcode project should be included.

**Comment by tinder-maxwellelliott** [comment]
> I think it'd be great to cover that stdout/stderr doesn't get replayed for cache hits. Maybe "Why do warnings seem to disappear randomly from Xcode?"

I get asked this all the time
