### ISSUE TITLE
Feature Request: Show BUILD files in the Project navigator

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#300]
Being able to see and edit BUILD files in Xcode is useful, especially with Build with Bazel. We should show the BUILD files in the Project navigator.

Development steps:
- In `input_files.collect()` add https://docs.bazel.build/versions/main/skylark/lib/ctx.html#build_file_path to `extra_files`
- In `Generator.createFilesAndGroups` ensure that the `explicitFileType` for the BUILD files are `"text.script.python"` (if a better one doesn't exist)

**Comment by jpsim** [comment]
Mind if I give this a shot? I'd love to contribute something small but useful to the project.

**Comment by brentleyjones** [comment]
That would be awesome, thanks! ❤️
