### ISSUE TITLE
Bug: Build failure copying non-existing Info.plist in macos_unit_test

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#303]
## Describe the bug

We have a small macOS utility with unit tests. Unit tests and the test bundle generate successfully, but running tests on the test bundle results in a failure on `rsync`

## Reproduction steps

1. Create a `macos_unit_test` + `swift_library`
2. Generate an `xcodeproj` including the `macos_unit_test`.
3. Select the test scheme (currently named `MyTests.__internal__.__test_bundle`) and run the test action.
4. Build fails on an rsync

```
PhaseScriptExecution Copy\ Files /Users/ekerber/Library/Developer/Xcode/DerivedData/BPGeneratorXcode-dwuzirkbvvcqzscgacptcxyrgzxx/Build/Intermediates.noindex/BPGeneratorXcode.build/rules_xcodeproj/GenerateBazelFiles/Script-DC8C0BF34938CC62E3BAC404.sh (in target 'Bazel Generated Files' from project 'BPGeneratorXcode')
    cd /Users/ekerber/dev/slack/slack-objc
    /bin/sh -c /Users/ekerber/Library/Developer/Xcode/DerivedData/BPGeneratorXcode-dwuzirkbvvcqzscgacptcxyrgzxx/Build/Intermediates.noindex/BPGeneratorXcode.build/rules_xcodeproj/GenerateBazelFiles/Script-DC8C0BF34938CC62E3BAC404.sh

rsync: link_stat "/private/var/tmp/_bazel_ekerber/dd323d2a4ff53820c11ccc0d5aebe791/execroot/slack-objc/bazel-out/applebin_macos-darwin_x86_64-dbg-ST-b590acde83ea/bin/tooling/bpgenerator/BoilerplateGeneratorTests.__internal__.__test_bundle-intermediates/Info.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/66382bca-8bca-11ec-aade-6613bcf0e2ee/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
```

In this case, Info.plist does not exist but the parent directory above does.

## Expected behavior
Builds and tests

## Versions
- Bazel: 5.1
- rules_xcodeproj: 0.2.0
- rules_apple: `f52f838c8ce88e2f78894b9047a09b0956c7834b`
- rules_swift: `0.26.0`

**Comment by brentleyjones** [comment]
Are you running Xcode in Rosetta mode, but generating the project in arm64 mode?

**Comment by erikkerber** [comment]
Closing as this was a forced arch/platform mismatch.
