### ISSUE TITLE
Update Xcode scheme generation code to support slashes

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#371]
If slashes (/) appear in name for `XCScheme`, a missing folder error will occur when writing the scheme files. It may be possible to update `XcodeProj` to handle this better. If so, we should remove the code that removes slashes in the `schemeName` property defined in `PBXTarget+Extensions.swift`.

**Comment by brentleyjones** [comment]
I might have been wrong here. Seems there is no field for the name, it's just the filename.
