### ISSUE TITLE
Bug: Use `fragment.objc.copts_for_current_compilation_mode` 

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#415]
## Describe the bug

I noticed that Bazel was passing `-fstack-protector-all` for PCM and objc libraries. We aren't, because that is only set via `fragment.objc.copts_for_current_compilation_mode`, and in the case of Swift, if that is empty it sets the equivalent of it.

## Expected behavior

We should follow rules_swift's behavior and set these copts. And for `objc_library` (or rather any targets that have a `ObjcProvider`?) we should apply these copt in addition to the ones we get from cc_toolchain.

**Comment by brentleyjones** [comment]
Also, for `rules_swift` it seems to only use `fragment.objc.copts` + `fragment.objc.copts_for_current_compilation_mode`, and nothing from cc_toolchain. So we should follow the same for Swift. For non-swift I believe it still also uses the cc_toolchain ones. We should test all of these either way and compare.

**Comment by brentleyjones** [comment]
We need to also filter out `-g` from the `-Xcc` flags.

**Comment by maxwellE** [comment]
Where should I start looking in the code to fix this issue?

**Comment by brentleyjones** [comment]
`xcodeproj/internal/optz.bzl`

**Comment by brentleyjones** [comment]
This is causing issues with SwiftUI in BwX mode, as it complains about some of the values set incorrectly here. Even after we fix it, we might have to conditionally set values for previews like we do for indexing.

**Comment by brentleyjones** [comment]
Specifically SwiftUI previews code manually removes `-g`, which breaks things since we then get a command line like this:
```
-Xcc -Xcc -something-else
```

**Comment by tinder-maxwellelliott** [comment]
Is this exact bug only for BWX?

**Comment by brentleyjones** [comment]
You'll see some flags, but it's not the correct ones. It impacts BwX the most, but it can impact indexing or SwiftUI Previews in BwB.

**Comment by DavidGoldman** [comment]
Also need to use `fragments.objc.copts` in order to fetch the `--objccopt` flags from bazel.
