### ISSUE TITLE
Bug: Schemes output differs slightly from what Xcode wants

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#421]
## Describe the bug

```diff
 <?xml version="1.0" encoding="UTF-8"?>
 <Scheme
    LastUpgradeVersion = "1320"
-   version = "1.3">
+   version = "1.7">
    <BuildAction
       parallelizeBuildables = "YES"
       buildImplicitDependencies = "YES">
@@ -52,13 +52,13 @@
       buildConfiguration = "Debug"
       selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
       selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
+      customLLDBInitFile = "$(BAZEL_LLDB_INIT)"
       launchStyle = "0"
       useCustomWorkingDirectory = "NO"
       ignoresPersistentStateOnLaunch = "NO"
       debugDocumentVersioning = "YES"
       debugServiceExtension = "internal"
-      allowLocationSimulation = "YES"
-      customLLDBInitFile = "$(BAZEL_LLDB_INIT)">
+      allowLocationSimulation = "YES">
       <BuildableProductRunnable
          runnableDebuggingMode = "0">
          <BuildableReference
```

## Reproduction steps

Edit a scheme in Xcode, revert your edits in Xcode. Compare the XML.

## Expected behavior

XML should be unchanged, as Xcode shouldn't adjust anything to its expected values.

## Additional context

For the `customLLDBInitFile` ordering it looks like we will need to patch (and try to upstream) XcodeProj to set the order correctly.

**Comment by maxwellE** [comment]
Put up this PR in XcodeProj https://github.com/tuist/XcodeProj/pull/686/files. Should fix the ordering issues

**Comment by brentleyjones** [comment]
I think this is still slightly off:
<img width="497" alt="CleanShot 2022-06-12 at 19 45 56@2x" src="https://user-images.githubusercontent.com/158658/173260973-6b29dd16-6167-415d-b51c-41d41f5b558a.png">

**Comment by maxwellE** [comment]
Put up a new XcodeProj PR [here](https://github.com/tuist/XcodeProj/pull/689) for the missed TestAction ordering
