### ISSUE TITLE
Bug: Previews are not available in `swift_library`s

### ISSUE THREAD

**Issue by achew22** [buildbuddy-io/rules_xcodeproj#640]
## Describe the bug

If you compose your project out of lots of small `swift_library` targets, it is not possible to use xcode previews to interactively develop your UI.

## Reproduction steps

Using the basic xcodeproj app, create a new `swift_library` target in a separate directory. In this directory create

`BUILD`
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SlotFeature", # Name chosen to mirror the internals of my project but I don't believe it matters
    srcs = glob(["*.swift"]),
    module_name = "SlotFeature",
    visibility = ["//:__subpackages__"],
)
```

In a file called `MyView.swift` create an extremely basic view like this (with a preview):

```swift
public struct MyView: View {
  public var body: some View {
    Text("Hi mom")
  }
}

struct MyView_Previews: PreviewProvider {
  static var previews: some View {
    MyView()
  }
}
```

Depend upon this new `swift_library` in the application and regenerate the xcodeproj.

Open the xcodeproj.

Turn on the live preview feature in xcode with `option+command+enter`. Tell it to resume if it says it's paused.

Get this error:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/37206/177223987-7f4d21be-b398-42ef-858c-b9a1ab12ed2d.png">

## Expected behavior

I would expect the preview to load.

## Versions
- Bazel:  5.2.0
- rules_xcodeproj: 5710480e1c726b34ecc45f1abf1bedb0d8054a46
- rules_apple: The one from xcodeproj @ this commit
- rules_swift:The one from xcodeproj @ this commit

**Comment by brentleyjones** [comment]
This is a limitation of Xcode, not rules_xcodeproj. As part of our [design goals](https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/doc/design/high-level.md), we will replicate your Bazel build as much as possible, which means swift_library is a static library.

There are ways to make Bazel create and link dynamic frameworks instead. Right now rules_xcodeproj does t support that, but it will eventually, and that is how you would get previews for your libraries. For now though, application targets support previews.

**Comment by Ayatuas** [comment]
I am still confused on how to make previews work. Bazel has no rule compiling swift code directly into "framework" (like swift_framework or swift_static_framework ?), and ios_application\ios_framework has no 'srcs' attribute. As a result, I cannot use swiftui previews with any swift source code in generated projects cause they are all included by swift_library, which has static library product type. Maybe provide configs to change swfit_library‘s product type to static framework would be useful?

**Comment by BalestraPatrick** [comment]
@Ayatuas There's an example here: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/examples/integration/UI/BUILD

Basically `ios_framework` can depend on `swift_library`.

**Comment by Ayatuas** [comment]
@BalestraPatrick  The "UIFramework.iOS" and "UI" are in the same package, and "ContentView.swift" is included in "UIFramework.iOS"'s compiler souce as expected. But after I append another swift_library target to "UIFramework.iOS"'s deps attribute, this would be broken. Is this by design or by accident?

Before
<img width="759" alt="image" src="https://user-images.githubusercontent.com/28378181/197383199-c466c027-633a-4aca-869d-3f3351eca214.png">

After
<img width="824" alt="image" src="https://user-images.githubusercontent.com/28378181/197383114-302bb15c-2a83-445f-967a-73830434f739.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/28378181/197383126-71f89819-0a99-40d5-8810-8f20863c93ff.png">

**Comment by brentleyjones** [comment]
That's by design. A bundling Target can only have one direct dependency, otherwise they can't be merged together. You can add a dependency to the dependency though (and the same for the framework, as frameworks can list `frameworks` like `UI` does on `Lib`).

**Comment by Ayatuas** [comment]
👍
