### ISSUE TITLE
Support `objc_library`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#69]
https://bazel.build/reference/be/objective-c#objc_library

- [x] https://github.com/buildbuddy-io/rules_xcodeproj/issues/68
- [x] https://github.com/buildbuddy-io/rules_xcodeproj/pull/147
- [x] Support `alwayslink`: #608 
- [x] Support `pch`: https://github.com/buildbuddy-io/rules_xcodeproj/pull/280
- [ ] Support `runtime_deps`
- [x] Support `sdk_dylibs`: #372
- [x] Support `sdk_frameworks`: https://github.com/buildbuddy-io/rules_xcodeproj/pull/278
- [x] Support `sdk_includes`: https://github.com/buildbuddy-io/rules_xcodeproj/pull/1660
- [x] Support `weak_sdk_frameworks`: https://github.com/buildbuddy-io/rules_xcodeproj/pull/278

**Comment by maxwellE** [comment]
@brentleyjones I think some of this issues' sub tasks are now completed

**Comment by brentleyjones** [comment]
I checked off the ones I'm sure of. We need examples of the remaining ones.

**Comment by brentleyjones** [comment]
While we don't have an example for `runtime_deps`, unless a bug is reported, I'm claiming this is done.
