### ISSUE TITLE
Bug: watchOS app installation fails in BwB

### ISSUE THREAD

**Issue by BalestraPatrick** [buildbuddy-io/rules_xcodeproj#703]
## Describe the bug
Installing a watchOS app in the Simulator fails with `WatchKit 1.0 apps are no longer installable on this watchOS version.`. This is reproducible in the `multiplatform` example by making sure it uses BwB. 

## Reproduction steps
Add `build_mode = "bazel"` here: https://github.com/buildbuddy-io/rules_xcodeproj/blob/4147859475311397cb894b6c43fb1f9dfab30965/examples/multiplatform/BUILD#L13
and build the Watch App scheme in the project. The reason is because the watchOS extension isn't bundled inside the Watch App.
<img width="558" alt="Screenshot 2022-07-08 at 11 10 53 PM" src="https://user-images.githubusercontent.com/3658887/178070871-27698ba7-1df1-45a6-b0db-33d7bec6d31c.png">

Manually adding it fixes the issue.
<img width="558" alt="Screenshot 2022-07-08 at 11 10 39 PM" src="https://user-images.githubusercontent.com/3658887/178070904-53d37c65-3d6f-4cb3-a4f6-a5ba6ee3f699.png">

## Expected behavior
Watch app should install and launch correctly.

## Versions
- Bazel:5.2.0
- rules_xcodeproj: 4147859475311397cb894b6c43fb1f9dfab30965

**Comment by brentleyjones** [comment]
Thanks for the report. I thought I had this covered already, but it seems that I missed it and/or it's specific to BwB. I'll get it fixed early next week.
