### ISSUE TITLE
Bug: Building with external `rules_spm` package fails with BwX

### ISSUE THREAD

**Issue by luispadron** [buildbuddy-io/rules_xcodeproj#705]
## Describe the bug
When building in BwX mode, targets which depend on a `rules_spm` SPM package dependency fail to build. The error given by Xcode is `No such module found <SPM-Module>`

### Archive

[rules_spm_BwX_no_module_found.zip](https://github.com/buildbuddy-io/rules_xcodeproj/files/9077303/rules_spm_BwX_no_module_found.zip)

## Reproduction steps
1. Download the archive
2. Run `bazel run xcodeproj --apple_platform_type=macos`
3. Attempt to build `cli` target

## Expected behavior
The target build successfully and external packages can be imported and found by Xcode.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 57dabff76c9409dc9e1d0e77ae784b916e634888
- rules_apple: <from 57dabff76c9409dc9e1d0e77ae784b916e634888>
- rules_swift: <from 57dabff76c9409dc9e1d0e77ae784b916e634888>
- rules_spm: [695570b5d238ed805685ac87a7ec696021e6fa4f](https://github.com/cgrindel/rules_spm/commit/695570b5d238ed805685ac87a7ec696021e6fa4f)

## Additional context

This might not be fully supported yet but I did notice #311 was closed so opening this since there are still some issues.

**Comment by brentleyjones** [comment]
The main issue here is accounting for the way that rules_spm handles clang modules. Bazel sees them with `-I` becauae of how files are copied around in `bazel-out`. We can't really fix that as is because those files can't be easily copied to Derived Data. The real fix is https://github.com/buildbuddy-io/rules_xcodeproj/issues/633.

**Comment by brentleyjones** [comment]
Turns out in this case it was something simpler: #743. There are other rules_spm issues like I mentioned above, but this will now be fixed.

**Comment by luispadron** [comment]
Sweet! Excited to try this out thanks again for your work!
