### ISSUE TITLE
Feature Request: Support rules_ios's `apple_framework`

### ISSUE THREAD

**Issue by hzfanfei** [buildbuddy-io/rules_xcodeproj#715]
I user apple_framework in my project build file, bug when I run [bazel run //:xcodeproj], error is outputed fail("Could not find product for target {}".format(target.label))

**Comment by brentleyjones** [comment]
Do you have an example repro I can use to debug this? We haven't put any work towards making intermediate framework rules work, so this doesn't necessarily surprise me. We have an upcoming milestone dedicated to working on them though, and their priority can be raised based on demand.

**Comment by hzfanfei** [comment]
https://github.com/hzfanfei/learn_bazel.git
I quickly built a demo with two branches.
`cd ios-app
bazel run //:xcodeproj
`
the result at main branch is run fine
the result at apple_framework branch is wrong. apple_framework branch use apple_framework

**Comment by brentleyjones** [comment]
Thank you. I'll look at it soon.

**Comment by brentleyjones** [comment]
Using rules_xcodeproj 0.6.0 and `build_mode = "bazel"` I was able to get the project to build and run:
<img width="1296" alt="CleanShot 2022-07-13 at 15 23 55@2x" src="https://user-images.githubusercontent.com/158658/178827785-a87883ce-4df4-4d0d-ba81-bfdee456c2f8.png">

BwX (`build_mode = "xcode"`, the current default) has issues with linking, which will be resolved in [Milestone 0.9](https://github.com/buildbuddy-io/rules_xcodeproj/milestone/14).

**Comment by brentleyjones** [comment]
So this now works in BwB mode again, but BwX mode is blocked by supporting the VFS overlay that the rule uses (which is similar to #619). Because of the path manipulation needed for BwX mode, this might never be "properly" supported in BwX mode.

I'm moving this to the 1.0 milestone for now, and I'm thinking about how to handle situations like this in BwX mode.

**Comment by brentleyjones** [comment]
I believe this works in BwB mode now. BwX mode has an error at generation since we can't support VFS overlays in BwX mode.
