### ISSUE TITLE
Support `objc_import`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#73]
https://bazel.build/reference/be/objective-c#objc_import

**Comment by brentleyjones** [comment]
I'm pretty sure we already support this, and just need an example in the fixtures. Would you like to do that @maxwellE?

**Comment by BalestraPatrick** [comment]
Isn't this covered by this example already? https://github.com/buildbuddy-io/rules_xcodeproj/blob/e1c0f4f3aa32c5679a888714a2b40f512beed3a2/examples/integration/CommandLine/external/BUILD.tpl#L19-L24

**Comment by brentleyjones** [comment]
This one is, thanks!
