### ISSUE TITLE
Support `apple_bundle_version`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#74]

**Comment by cgrindel** [comment]
@brentleyjones Based upon your comment in #286, I will take a look to see if these values are being passed through properly.

**Comment by cgrindel** [comment]
Xcode App Version => MARKETING_VERSION in pbxproj
Xcode Build Version => CURRENT_PROJECT_VERSION in pbxproj

**Comment by brentleyjones** [comment]
I know we don't set those to match `apple_bundle_version`, but I wonder if we _need_ to, since the Info.plists that we show in Xcode are the ones that bazel generates, which would already have the correct versions set.

Thinking about it, there probably is still use for them being set correctly, for tools that parse the project file and do things based on those values.

**Comment by cgrindel** [comment]
I think that it would be very confusing to the user if the version info does not match what was in their build file.

**Comment by brentleyjones** [comment]
More than enough reason for me for us to have them reflect properly 😄.

**Comment by cgrindel** [comment]
After setting up the `watchos_app` to properly use `apple_bundle_version`, I was able to see version information flow through to the Xcode project. Here are the steps:

1. Navigate to the root of the `rules_xcodeproj` repo.
2. Generate the Xcode project: `bazel run //examples/watchos_app:xcodeproj`.
3. Open the Xcode project: `open examples/watchos_app/WatchOS\ App.xcodeproj`
4. Select the `Setup` scheme (`Product` > `Scheme` > `Setup`).
5. Execute the build for the `Setup` scheme (`Product` > `Build`).
6. Select the `Bazel Generated Files` scheme (`Product` > `Scheme` > `Bazel Generated Files`).
7. Execute the build for the the `Bazel Generated Files` scheme (`Product` > `Build`).
8. Close Xcode.
9. Open the Xcode project: `open examples/watchos_app/WatchOS\ App.xcodeproj`.

After doing those steps, selecting the project root (`WatchOS App`), clicking on the `General` tab, and selecting the `Example` target under `TARGETS`, the `Identity` section shows the version information that was specified using `apple_bundle_version`. The same is true when looking at the `Identify` info for `ExampleWatchKitApp`.

**Comment by brentleyjones** [comment]
So given that, there should be less confusion regarding versions. I still think we should parse the version info and set `MARKETING_VERSION` and `CURRENT_PROJECT_VERSION` as well, BUT that is really low priority and we shouldn't worry about it right now.

**Comment by brentleyjones** [comment]
Btw, step 4 and 5 shouldn't be needed, as `Bazel Generated Files` depends on `Setup`.

**Comment by cgrindel** [comment]
I just confirmed that one only needs to run `Bazel Generated Files`. 

For my future self, the `MARKETING_VERSION` and `CURRENT_PROJECT_VERSION` appear in the Xcode UI by doing the following:

1. Select the root project (`WatchOS App`).
2. In the center pane, select the `WatchOS App` under `PROJECT`.
3. Click on `Build Settings` tab.
4. Scroll the middle pane to the `Versioning` section.

You should see the `Current Project Version` and the `Marketing Version`.

**Comment by cgrindel** [comment]
@brentleyjones Not specifying the `MARKETING_VERSION` and the `CURRENT_PROJECT_VERSION`, does not seem to adversely affect the generated project. I suggest that we do not set them as the values that are set are not consistent with the versions specified in the `apple_bundle_version` or directly in the `Info.plist`. 

If you are OK with that I will submit a PR that 
1. Updates the `watchos_app` example to properly use `apple_bundle_version`
2. Removes the setting of the `MARKETING_VERSION` and the `CURRENT_PROJECT_VERSION` values.

**Comment by brentleyjones** [comment]
Yep, I'm good with removing the `MARKETING_VERSION` and `CURRENT_PROJECT_VERSION` values. :+1:

Maybe we never set them in the future, or maybe we find a way to detect parse them from the Info.plist. Regardless, that is a future enhancement.
