### ISSUE TITLE
Bug: fails to link with cc_library dep

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#763]
## Describe the bug
Xcode projects which have a `cc_library` dep fail to list the dep's .a output in the link parameters, and therefore linking fails with "Undefined symbol" errors. 

## Reproduction steps
1. Clone https://github.com/jfirebaugh/rules_xcode_reduction
2. Observe that `bazel run :app` builds and runs successfully. That is, the `macos_application` and `cc_library` targets are correctly defined.
3. Run `bazel run :xcodeproj && open app.xcodeproj/` and then attempt to build the "app" scheme in Xcode.
4. Observe the following link error:
```
Undefined symbols for architecture x86_64:
  "say_hello()", referenced from:
      _main in main.o
```

## Expected behavior
App links and runs successfully.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 0.6.0
- rules_apple: As installed by rules_xcodeproj 0.6.0
- rules_swift: As installed by rules_xcodeproj 0.6.0

**Comment by brentleyjones** [comment]
I'll look into this tonight. This surprises me, as this is covered in all of the existing examples.

I did do a similar fix on `main` today though, can you try `HEAD`?

**Comment by brentleyjones** [comment]
One of the various fixes in `main` addressed this. Thanks for the bug report! 0.7.0 should be released next week sometime, but in the meantime, using current `HEAD` should work well for you.
