### ISSUE TITLE
"Decoded elements aren't unique" error

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#764]
As of c538247afae41ffef463b6d1d1856453b0b21fd2, I get an error when trying to run the xcodeproj target:

```
ERROR: Internal precondition failure:
At codingPath [targets, Index 55, linkerInputs, staticLibraries]: Decoded elements aren't unique (first duplicate at offset 73)
Please file a bug report at https://github.com/buildbuddy-io/rules_xcodeproj/issues/new?template=bug.md
```

This seems to be a recent regression. I do not get this error with 435cd30e1d4da0977eb9c7d63c98f4976dd856ae.

**Comment by jfirebaugh** [comment]
Bisects to 22ac870b592ad4b0fa21b00e7df0780a124b6592.

**Comment by brentleyjones** [comment]
I see the bug. I'll have a fix tomorrow.
