### ISSUE TITLE
Bug: Failure to generate project due to generated `apple_resource_group`

### ISSUE THREAD

**Issue by rockwotj** [buildbuddy-io/rules_xcodeproj#783]
## Describe the bug
Hello! I'm taking a stab at using this instead of XCHammer for our builds and is seems that there may be an issue with generated inputs into and `apple_resource_group`.

Here is the error:

```
error: The files that Bazel generated don't match what the project expects. Please regenerate the project.
error: bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-a0c3a8d1fbfb/bin/shortwave/design/assets/Assets.xcassets
bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-a0c3a8d1fbfb/bin/shortwave/design/icons/Assets.xcassets
error: If you still get this error after regenerating your project, please file a bug report here: https://github.com/buildbuddy-io/rules_xcodeproj/issues/new?template=bug.md.
```

## Reproduction steps

Roughly we have some svgs checked into our repo and we have a small python script that moves them to the right directory and also adds the `Contents.json` file for each of the assets.

Here's roughly what is going on:

```starlark
py_binary(
    name = "ios_svg_generator",
    srcs = ["generate_ios_svg.py"],
    main = "generate_ios_svg.py",
    python_version = "PY3",
)

# In reality there are a couple dozen of these behind a macro.
run_binary(
        name = "generate_foo_svg",
        outs = [
          "Assets.xcassets/foo.imageset/foo.svg",
          "Assets.xcassets/foo.imageset/Contents.json"
        ],
        args = [
            "--input=$(location images/foo.svg)",
            "--svg_output=$(location Assets.xcassets/foo.imageset/foo.svg)",
            "--meta_output=$(location Assets.xcassets/foo.imageset/Contents.json)",
        ],
        srcs = ["images/foo.svg"],
        tool = ":ios_svg_generator",
)

filegroup(
    name = "ios_assets",
    srcs = [":generate_foo_svg"],
)

apple_resource_group(
    name = "ios_asset_resources",
    resources = [":ios_assets"],
    visibility = ["//visibility:public"],
)
```

## Versions
- Bazel: 5.2
- rules_xcodeproj: 0.6
- rules_apple: 1.0.1

**Comment by rockwotj** [comment]
Note that this is using the default of building with XCode. I'll trying switching to build with Bazel and see if that fixes things (I believe I'd prefer that mode anyways)

**Comment by brentleyjones** [comment]
Resources are a pain 😅. I recommend using BwB for now. I'll look into this though, as it should be supported.

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/pull/621 regressed the earlier fix for this: https://github.com/buildbuddy-io/rules_xcodeproj/pull/510
