### ISSUE TITLE
Bug: BwB doesn't stub out C++ linking

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#786]
## Describe the bug
In a project using `build_mode = "bazel"`, with a `cc_library` dep of the `macos_application`, when the `cc_library` has `srcs`, the link step can't find the corresponding .a.

## Reproduction steps
[Minimized reproduction.](https://github.com/jfirebaugh/rules_xcode_reduction/tree/786)
Run `bazel run :xcodeproj` and then build the resulting project. It fails with:
```
ld: file not found: /Users/john/Library/Developer/Xcode/DerivedData/app-dgjuglrhibaposarleeqrtxtrlcs/Build/Intermediates.noindex/app.build/bazel-out/macos-x86_64-min10.12-applebin_macos-darwin_x86_64-dbg-ST-3ceb28bca76f/bin/app/Objects-normal/x86_64/lib.o
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Expected behavior
Build succeeds.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 29a91e3eb5c8f481c998278ac8d1ccd1ae102d39
- rules_apple: As installed by above
- rules_swift: As installed by above

**Comment by jfirebaugh** [comment]
https://github.com/jfirebaugh/rules_xcode_reduction/tree/786

**Comment by jfirebaugh** [comment]
Thanks, I have a working Xcode project now!

**Comment by brentleyjones** [comment]
Woot! That's awesome. Please continue to file any feedback you have/bugs you find 😄.
