### ISSUE TITLE
Bug: `generator` crashes at runtime if `--host_macos_minimum_os` isn't set correctly

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#798]
## Describe the bug
My colleague @cricklet is receiving the following error when trying to build an `xcodeproj` target:

```
❯ bazel build //fullscreen:xcode
INFO: Analyzed target //fullscreen:xcode (3 packages loaded, 1499 targets configured).
INFO: Found 1 target...
ERROR: /Users/kenrick/figma/figma/fullscreen/BUILD.bazel:1166:10: GenerateXcodeProj fullscreen/xcode.xcodeproj failed: (Aborted): generator failed: error executing command
  (cd /private/var/tmp/_bazel_kenrick/5bddae61325b18dc7cde052c88d77833/sandbox/darwin-sandbox/193/execroot/figma && \
  exec env - \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/com_github_buildbuddy_io_rules_xcodeproj/tools/generator/generator bazel-out/darwin_arm64-fastbuild/bin/fullscreen/xcode_spec.json bazel-out/darwin_arm64-fastbuild/bin/fullscreen/xcode_xccurrentversions bazel-out/darwin_arm64-fastbuild/bin/fullscreen/xcode_extensionpointidentifiers external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/bazel_integration_files bazel-out/darwin_arm64-fastbuild/bin/fullscreen/xcode.xcodeproj fullscreen/fullscreen.xcodeproj bazel)
# Configuration: b3bf8d2de0ebd02e8c0eca177af5323c5fd8f43503bddf53c8022478b7613a85
# Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
dyld[48697]: Symbol not found: _swift_isUniquelyReferenced_nonNull
  Referenced from: /private/var/tmp/_bazel_kenrick/5bddae61325b18dc7cde052c88d77833/execroot/figma/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/com_github_buildbuddy_io_rules_xcodeproj/tools/generator/generator
  Expected in: /usr/lib/swift/libswiftCore.dylib
Target //fullscreen:xcode failed to build
INFO: Elapsed time: 1.548s, Critical Path: 0.13s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

## Expected behavior
Xcode project is generated successfully.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 019c10ee5f8b6ff74433570311245d2a3df49ea8
- rules_apple: 1.0.1
- rules_swift: As installed by `swift_rules_dependencies` from rules_xcodeproj
- macOS: 12.1
- Xcode: 13.4.1

## Additional context
When trying to diagnose the issue, I found https://stackoverflow.com/questions/55550759/swift-why-is-symbol-not-found, but I am not sure how to interpret this. In this case there is only a single macOS version in play, so I'm not sure how Swift 4 and 5 would be getting mixed.

**Comment by brentleyjones** [comment]
Does setting `build --host_macos_minimum_os=12.1` fix it?

**Comment by cricklet** [comment]
That worked, thanks!

**Comment by brentleyjones** [comment]
Awesome. Hazel defaults the minimum os for macOS to the version of the SDK, and in Xcode 13.4.1 that is macOS 12.3.

By 1.0's release we will precompile the generator as a fat binary, so you won't need this flag anymore.

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/issues/223

**Comment by erikkerber** [comment]
>  we will want to support people using non-release versions as well

Or anyone stuck on macOS n-1 for 6 months after any major release :)

**Comment by brentleyjones** [comment]
The optimized releases would mean that we have a compiled binary and this bug wouldn't happen. So I meant that if someone wanted to use a non-release version of rules_xcodeproj (developers or commit based checkouts) it would be nice if they didn't have to set the flag globally.
