### ISSUE TITLE
Bug: Files and folders don't resolve in Xcode until build or next open

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#848]
## Describe the bug

When first generating an Xcode project, some files and folders don't resolve in Xcode. They're red in the project navigator, files aren't available to quick-open, search results from those files don't show up etc.

If I then build a target, the _folders_ resolve and are no longer red, but the files are still red and not resolved.

If I then close and re-open the Xcode project, the files now resolve.

|First Open|After Build 1| After Build 2|After Re-Open|
|-|-|-|-|
|![image](https://user-images.githubusercontent.com/474794/182147429-929e4adf-3a37-4e7b-a8b2-171f55ccd71f.png)|![image](https://user-images.githubusercontent.com/474794/182147454-de1d428a-febb-4e15-803c-f60e28276b11.png)|![image](https://user-images.githubusercontent.com/474794/182147490-71745efc-2db8-45f4-bc0c-7520a3997ed8.png)|![image](https://user-images.githubusercontent.com/474794/182147526-c05b0579-69c6-41fe-9b62-6dcb29852ed2.png)|

## Reproduction steps

1. Clone https://github.com/jpsim/swiftlint-bazel-example
2. Generate the Xcode project: `bazel run :swiftlint_xcodeproj`
3. Open the Xcode project: `xed .`
4. Notice the unresolved folders and files in the project navigator
5. Build the `swiftlint` scheme
6. Notice the folders are now resolved
7. Close & re-open the Xcode project
8. Notice the files are now resolved

## Expected behavior

Files and folders should resolve correctly when first opening a generated Xcode project.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 1cc0245336bf17d0a8483da21048faeb14ac53a9
- rules_apple: 1.0.1
- rules_swift: 1.0.0

**Comment by brentleyjones** [comment]
This is odd. The folders should all be there, but the files are expected to be red now (we now only pre-generate entitlements as part of project generation), and the only files that will get generated are the ones for the target being built.

I'll dig into this today, and see why we aren't generating the folders correctly here.

**Comment by brentleyjones** [comment]
I see it now. As always, thanks for the bug report!
