### ISSUE TITLE
Bug: Code completion does not work for external repositories

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#858]
## Describe the bug

Code completion does not work for external repositories. It works for local sources however.

|Local Files|External Files|
|-|-|
|![image](https://user-images.githubusercontent.com/474794/182388487-0fcc1044-5468-4ed8-ac93-d6eeaa60c904.png)|![image](https://user-images.githubusercontent.com/474794/182388430-31867a0f-131a-4f48-a4c8-2f3593f9829a.png)|

## Reproduction steps

1. Clone https://github.com/jpsim/swiftlint-bazel-example
2. Run `bazel run :swiftlint_xcodeproj && xed .`
3. Build the SwiftLintFramework scheme
4. Type `visit` in the body of the `ForceCastRuleVisitor` located in the `ForceCastRule.swift` file then press escape to trigger the code completion modal

Following the same steps in the [`rules_xcodeproj` branch of SwiftLint](https://github.com/realm/SwiftLint/compare/rules_xcodeproj) works just fine.

## Expected behavior

Code completion should work for both local files and files from external repositories.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 7cdff3362ea8fffae42097b9276ff8a6ffbee2fb
- rules_apple: 1.0.1
- rules_swift: 1.0.0

## Additional context

1. I see the same behavior with BwB and BwX
2. Files in a `local_repository` like [`swiftlint_extra_rules/ForbiddenVarRule.swift`](https://github.com/jpsim/swiftlint-bazel-example/blob/main/swiftlint_extra_rules/ForbiddenVarRule.swift) also don't have working code completion
3. _Some_ code completion still works, such as accessing members on an instance, like if I type `node.` like the following screenshot:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/474794/182391874-742add7e-1ed2-4d5d-8cb0-61688a2cf0b4.png">

However, I still see less information than if it fully worked, such as this local files case that also shows documentation and more accurate type information:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/474794/182391292-c830e307-c27d-4012-b762-e84669b2fc9b.png">

**Comment by brentleyjones** [comment]
Thank you for the detailed reproduction steps. I'll dig into this soon.

**Comment by brentleyjones** [comment]
This is interesting. It seems that when a symlink is part of the path, such as what we do for generated for external file groups, Xcode doesn't try to index those files. Switching it to the absolute path (i.e. `/private/var/tmp/_bazel_brentley/660e25fa6b462aefc923904b1f2cd129/external` in my case) made indexing work again.

I noticed some other indexing issues with your repro, so I'll be addressing those first, and then seeing what I can do on this front. #403 will help in the case of BwB, but ideally this works in BwX as well.
