### ISSUE TITLE
Bug: Code completion does not work for local repositories

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#888]
## Describe the bug

Code completion does not work for local repositories. It works for local sources and external repositories as of #880 however.

|Local Files|Local Repositories Files|
|-|-|
|![image](https://user-images.githubusercontent.com/474794/182388487-0fcc1044-5468-4ed8-ac93-d6eeaa60c904.png)|![image](https://user-images.githubusercontent.com/474794/182388430-31867a0f-131a-4f48-a4c8-2f3593f9829a.png)|

## Reproduction steps

1. Clone https://github.com/jpsim/swiftlint-bazel-example
2. Run `bazel run :swiftlint_xcodeproj && xed .`
3. Build the SwiftLintFramework scheme
4. Type `visit` in the body of the `ForbiddenVarRuleVisitor` located in the `ForbiddenVarRule.swift` file then press escape to trigger the code completion modal

## Expected behavior

Code completion should work for files from local repositories.

## Versions

- Bazel: 5.2.0
- rules_xcodeproj: ee7445ce80200aa80ce6d3342ac9b10451fe306c
- rules_apple: 1.0.1
- rules_swift: 1.0.0

## Additional context

See previous discussions in #858 and #880 for additional context.

**Comment by brentleyjones** [comment]
Context: https://github.com/buildbuddy-io/rules_xcodeproj/pull/880#issuecomment-1205715119

**Comment by brentleyjones** [comment]
I've thought of a way to address this, and I'll try to fix it in this next release.
