### ISSUE TITLE
Bug: `top_level_targets` attribute must be non empty when using custom schemes

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#914]
## Describe the bug

If I use custom schemes, I get the following error:

> ERROR: /.../BUILD:170:10: in top_level_targets attribute of xcodeproj rule //tools:swiftlint_xcodeproj: attribute must be non empty. Since this rule was created by the macro 'xcodeproj', the error might have been caused by the macro implementation

Specifying `top_level_targets` directly works fine.

## Reproduction steps

```
$ git clone git@github.com:realm/SwiftLint.git
$ cd SwiftLint
$ git checkout jp-rules_xcodeproj-schemes
$ bazel run :xcodeproj
ERROR: /src/SwiftLint/BUILD:55:10: in top_level_targets attribute of xcodeproj rule //:xcodeproj: attribute must be non empty. Since this rule was created by the macro 'xcodeproj', the error might have been caused by the macro implementation
ERROR: /src/SwiftLint/BUILD:55:10: Analysis of target '//:xcodeproj' failed
ERROR: Analysis of target '//:xcodeproj' failed; build aborted: 
INFO: Elapsed time: 0.119s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
```

The previous commit works fine by specifying `top_level_targets` directly.

## Expected behavior

I expected the project to generate successfully.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: da3c32c91653cd98d4cb0bb7ffe9ac81a6f5f800
- rules_apple: 1.0.1
- rules_swift: 1.0.0

**Comment by cgrindel** [comment]
This changed in the past two weeks. (I will post a link to the PR, in a moment.) Clients must provide `top_level_targets` even if they use custom Xcode schemes. There were some edge cases where the custom scheme inference logic would not suffice.

**Comment by cgrindel** [comment]
Related to #846 and #855.

**Comment by cgrindel** [comment]
@jpsim Let me know if you still run into issues after adding `top_level_targets`.

**Comment by jpsim** [comment]
So what should I put as `top_level_targets` then? The same targets that are in the custom schemes? It appears to be ignored in Xcode so I don't quite understand.

**Comment by cgrindel** [comment]
Also, note the comment that I added about the `build_action`. You should be able to remove it.

**Comment by jpsim** [comment]
ok I think I understand now. The custom schemes inspects the graph from `top_level_targets` so anything in the scheme needs to be in the transitive deps of the top level targets, otherwise it can't find them.

**Comment by cgrindel** [comment]
That is correct.

**Comment by jpsim** [comment]
ok, I think there could be some improvements to the error messages involved here, or the documentation for custom schemes, but I'll close this issue. Thanks for your help!
