### ISSUE TITLE
Support `swift_grpc_library`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#92]

**Comment by achew22** [comment]
I would be interested in taking a swing at this. Is there any documentation around (or even PRs doing similar work) on how to accomplish this?

**Comment by brentleyjones** [comment]
It's actually going to be a pretty tricky thing to tackle, and not a good First Issue to take on. This is because of the way that rules_swift uses an aspect to generate these actions. Thankfully, I'm going to tackle it starting Monday as part of the work on 0.5.0.

**Comment by achew22** [comment]
Darn! Sorry I won't be able to help out on this one. If there is anything that you think is reasonable to help out with, I'm more than happy to do it.

Also as an FYI, I upgraded rules_swift to use the 1.X series of gRPC in https://github.com/bazelbuild/rules_swift/pull/834. That changes things ever so slightly, so I just wanted to make you aware in case that matters

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/issues/91#issuecomment-1414179709

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/issues/1744
