### ISSUE TITLE
Bug: Can't set `test_action`

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#930]
## Describe the bug
If I set a `test_action` on a custom scheme, I get a "Target ... was not found" error:

> ERROR: Internal precondition failure:
> Target //experimental/swift:quic_stream_test was not found in the transitive dependencies of //:xcodeproj's `top_level_targets` attribute. Did you reference an alias (only actual target labels are supported in Scheme definitions)? Check that //experimental/swift:quic_stream_test is spelled correctly, and if it is, add it or a target that depends on it to //:xcodeproj's `top_level_targets` attribute.

## Reproduction steps

Branch: https://github.com/envoyproxy/envoy-mobile/compare/jp-custom-xcodeproj-schemes-bug

```
git clone git@github.com:envoyproxy/envoy-mobile.git
cd envoy-mobile
git checkout jp-custom-xcodeproj-schemes-bug
./bazelw run :xcodeproj
```

## Versions
- Bazel: 6.0.0-pre.20220706.4
- rules_xcodeproj: 0.7.0
- rules_apple: 8533494fa029f0fc44009c4532c191f349acf193
- rules_swift: 1.0.0

## Additional context

The test targets works if I don't pass custom schemes or if I set `scheme_autogeneration_mode = "all"`.

**Comment by brentleyjones** [comment]
Tests need to use the name of the internal target currently, which would probably be `//experimental/swift:quic_stream_test.__internal__.__test_bundle`

**Comment by brentleyjones** [comment]
Fixing #215 will prevent the need to specify the internal name.

**Comment by jpsim** [comment]
Ok let’s close as a duplicate of #215 then. Thanks!
