### ISSUE TITLE
Feature Request: Add support for custom working directory in launch action for custom Xcode scheme

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#933]
Related to #573.

It turns out that the [LaunchAction in XcodeProj](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Scheme/XCScheme%2BLaunchAction.swift) does not have a `customWorkingDirectory` attribute. (It does have `useCustomWorkingDirectory`.) This attribute will need to be added before custom working directory can be added in `rules_xcodeproj`.

**Comment by maxwellE** [comment]
https://github.com/tuist/XcodeProj/pull/720
