### ISSUE TITLE
Support `{ios,macos,tvos,watchos}_unit_test`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#95]
- [x] `ios_unit_test`
- [x] `macos_unit_test` (#267)
- [x] `tvos_unit_test` (#282)
- [x] `watchos_unit_test`

**Comment by erikkerber** [comment]
`macos_unit_test` not supported as of 0.1.0

**Comment by brentleyjones** [comment]
I've updated the comments.

**Comment by cgrindel** [comment]
At this point, I believe that we have rudimentary support for the listed unit test rules. Closing this issue.
