### ISSUE TITLE
Bug: Unable to omit build_for when creating build_target

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#959]
## Describe the bug

`build_for` defaults to `None` in `xcode_scheme.build_target`. This `None` value isn't converted into a default `build_for` value, resulting in a Codable error during generation:

```
ERROR: Internal precondition failure:
At codingPath [customXcodeSchemes, Index 0, buildAction, targets, Index 0, buildFor]: Cannot get keyed decoding container -- found null value instead.
```

## Reproduction steps

1. Create a custom scheme with a build target, omitting `build_for`:

```
        build_action = xcode_schemes.build_action([
            xcode_schemes.build_target(
                "//Foo:Bar
            ),
        ]),
```

This passes loading and analysis, but fails at project generation

## Expected behavior
Either:

- `build_for` defaults its values, per model_test.bzl
- A Starlark error is observed

## Versions
- Bazel: 5.3
- rules_xcodeproj: 739b8bb0
- rules_apple:
- rules_swift:

**Comment by jpsim** [comment]
Seeing the same thing with Envoy Mobile if you want an easy repro: `./bazelw run :xcodeproj` from https://github.com/envoyproxy/envoy-mobile

```
ERROR: Internal precondition failure:
At codingPath [customXcodeSchemes, Index 4, buildAction, targets, Index 0]: Expected to decode Dictionary<String, Any> but found a string/data instead.
```

**Comment by brentleyjones** [comment]
This is a slightly different issue, but another that should probably be addressed. I think we should accept a `String` or a `xcode_schemes.build_target` in the array inside of `xcode_schemes.build_action`. Thoughts @cgrindel?

**Comment by cgrindel** [comment]
@erikkerber @jpsim I am going to fix the fact that the default causes a failure. However, I am curious how you ran into this. I would not expect `xcode_schemes.build_target()` to be used unless you were overriding the `build_for`. Are you adding build targets that are not referenced elsewhere in the scheme?

**Comment by cgrindel** [comment]
> This is a slightly different issue, but another that should probably be addressed. I think we should accept a `String` or a `xcode_schemes.build_target` in the array inside of `xcode_schemes.build_action`. Thoughts @cgrindel?

@brentleyjones We can definitely add this ergonomic change. I am surprised that there are so many cases where someone is including build targets that are not referenced elsewhere in the scheme. Granted, I tend to think more about the BwB case.

**Comment by brentleyjones** [comment]
> @brentleyjones We can definitely add this ergonomic change. I am surprised that there are so many cases where someone is including build targets that are not referenced elsewhere in the scheme. Granted, I tend to think more about the BwB case.

Thank you. Seems like it would mainly be a custom `Decodable` implementation to allow both types to come though.

**Comment by cgrindel** [comment]
> Seems like it would mainly be a custom Decodable implementation to allow both types to come though.

I was thinking that we could detect it in the Starlark code and create the appropriate `struct` before generating the JSON.

**Comment by cgrindel** [comment]
I have been asked to prioritize #949. I am going to put up a PR to fix the default issue in a couple of minutes. The second PR will implement the string-only DSL that we discussed.

**Comment by erikkerber** [comment]
@cgrindel

>  I am surprised that there are so many cases where someone is including build targets that are not referenced elsewhere in the scheme. Granted, I tend to think more about the BwB case.

The biggest use case here is:

- A library target
- with tests for that library target

Common with a lot of highly-modular architectures, developers want the "Build" action to build just the library, while the "Test" action to run the tests (that depend on the library)

Granted sometimes I do wonder if these schemes shouldn't build the tests by default, but I can see use cases where you are making a lot of API changes and don't want to deal with fixing the tests in real-time.

**Comment by brentleyjones** [comment]
> Granted sometimes I do wonder if these schemes shouldn't build the tests by default, but I can see use cases where you are making a lot of API changes and don't want to deal with fixing the tests in real-time.

Xcode's default schemes don't build the tests by default, and I've gotten bug reports before this new behavior when they _did_ build the tests by default.

![image](https://user-images.githubusercontent.com/158658/186454469-0a8a650e-5fc5-42da-a10f-9c9b76901896.png)

**Comment by jpsim** [comment]
By default tests certainly shouldn't be built in my opinion. Especially if you have moderately heavy test-only dependencies, that can really slow down the first build of a module.
